//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.13 at 01:37:28 PM EDT 
//


package com.vzwcorp.pricinglab.vo.dvs.nbs;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="lineItemTypeCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="activationChangeLineItem" type="{}ActivationChangeLineItem" minOccurs="0"/>
 *         &lt;element name="disconnectLineItem" type="{}DisconnectLineItem" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "lineItemTypeCode",
    "activationChangeLineItem",
    "disconnectLineItem"
})
@XmlRootElement(name = "createOrderLineItem")
public class CreateOrderLineItem {

    protected String lineItemTypeCode;
    protected ActivationChangeLineItem activationChangeLineItem;
    protected DisconnectLineItem disconnectLineItem;

    /**
     * Gets the value of the lineItemTypeCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLineItemTypeCode() {
        return lineItemTypeCode;
    }

    /**
     * Sets the value of the lineItemTypeCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLineItemTypeCode(String value) {
        this.lineItemTypeCode = value;
    }

    /**
     * Gets the value of the activationChangeLineItem property.
     * 
     * @return
     *     possible object is
     *     {@link ActivationChangeLineItem }
     *     
     */
    public ActivationChangeLineItem getActivationChangeLineItem() {
        return activationChangeLineItem;
    }

    /**
     * Sets the value of the activationChangeLineItem property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActivationChangeLineItem }
     *     
     */
    public void setActivationChangeLineItem(ActivationChangeLineItem value) {
        this.activationChangeLineItem = value;
    }

    /**
     * Gets the value of the disconnectLineItem property.
     * 
     * @return
     *     possible object is
     *     {@link DisconnectLineItem }
     *     
     */
    public DisconnectLineItem getDisconnectLineItem() {
        return disconnectLineItem;
    }

    /**
     * Sets the value of the disconnectLineItem property.
     * 
     * @param value
     *     allowed object is
     *     {@link DisconnectLineItem }
     *     
     */
    public void setDisconnectLineItem(DisconnectLineItem value) {
        this.disconnectLineItem = value;
    }

}
