//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.13 at 01:37:28 PM EDT 
//


package com.vzwcorp.pricinglab.vo.dvs.nbs;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DataOverageInfoItem complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DataOverageInfoItem">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="domesticInternationIndicator" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="billingIDType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="billingID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ratingIDType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="unitOfMeasure" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="dataAllowanceQuantity" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="dataUsageQuantity" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="dataOverageQuantity" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="dataChargeAmount" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DataOverageInfoItem", propOrder = {
    "domesticInternationIndicator",
    "billingIDType",
    "billingID",
    "ratingIDType",
    "unitOfMeasure",
    "dataAllowanceQuantity",
    "dataUsageQuantity",
    "dataOverageQuantity",
    "dataChargeAmount"
})
public class DataOverageInfoItem {

    protected String domesticInternationIndicator;
    protected String billingIDType;
    protected String billingID;
    protected String ratingIDType;
    protected String unitOfMeasure;
    protected String dataAllowanceQuantity;
    protected String dataUsageQuantity;
    protected String dataOverageQuantity;
    protected String dataChargeAmount;

    /**
     * Gets the value of the domesticInternationIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDomesticInternationIndicator() {
        return domesticInternationIndicator;
    }

    /**
     * Sets the value of the domesticInternationIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDomesticInternationIndicator(String value) {
        this.domesticInternationIndicator = value;
    }

    /**
     * Gets the value of the billingIDType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBillingIDType() {
        return billingIDType;
    }

    /**
     * Sets the value of the billingIDType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBillingIDType(String value) {
        this.billingIDType = value;
    }

    /**
     * Gets the value of the billingID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBillingID() {
        return billingID;
    }

    /**
     * Sets the value of the billingID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBillingID(String value) {
        this.billingID = value;
    }

    /**
     * Gets the value of the ratingIDType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRatingIDType() {
        return ratingIDType;
    }

    /**
     * Sets the value of the ratingIDType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRatingIDType(String value) {
        this.ratingIDType = value;
    }

    /**
     * Gets the value of the unitOfMeasure property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUnitOfMeasure() {
        return unitOfMeasure;
    }

    /**
     * Sets the value of the unitOfMeasure property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUnitOfMeasure(String value) {
        this.unitOfMeasure = value;
    }

    /**
     * Gets the value of the dataAllowanceQuantity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDataAllowanceQuantity() {
        return dataAllowanceQuantity;
    }

    /**
     * Sets the value of the dataAllowanceQuantity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDataAllowanceQuantity(String value) {
        this.dataAllowanceQuantity = value;
    }

    /**
     * Gets the value of the dataUsageQuantity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDataUsageQuantity() {
        return dataUsageQuantity;
    }

    /**
     * Sets the value of the dataUsageQuantity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDataUsageQuantity(String value) {
        this.dataUsageQuantity = value;
    }

    /**
     * Gets the value of the dataOverageQuantity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDataOverageQuantity() {
        return dataOverageQuantity;
    }

    /**
     * Sets the value of the dataOverageQuantity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDataOverageQuantity(String value) {
        this.dataOverageQuantity = value;
    }

    /**
     * Gets the value of the dataChargeAmount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDataChargeAmount() {
        return dataChargeAmount;
    }

    /**
     * Sets the value of the dataChargeAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDataChargeAmount(String value) {
        this.dataChargeAmount = value;
    }

}
