//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.13 at 01:37:28 PM EDT 
//


package com.vzwcorp.pricinglab.vo.dvs.nbs;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for NafSfoInfo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="NafSfoInfo">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="nafSfoId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="nafPkgProcCategoryCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="nafLimitTypeCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="nafProductPrice" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="compatibleDaccCount" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element ref="{}compatibleDaccList" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NafSfoInfo", propOrder = {
    "nafSfoId",
    "nafPkgProcCategoryCode",
    "nafLimitTypeCode",
    "nafProductPrice",
    "compatibleDaccCount",
    "compatibleDaccList"
})
public class NafSfoInfo {

    protected String nafSfoId;
    protected String nafPkgProcCategoryCode;
    protected String nafLimitTypeCode;
    protected String nafProductPrice;
    protected String compatibleDaccCount;
    protected CompatibleDaccList compatibleDaccList;

    /**
     * Gets the value of the nafSfoId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNafSfoId() {
        return nafSfoId;
    }

    /**
     * Sets the value of the nafSfoId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNafSfoId(String value) {
        this.nafSfoId = value;
    }

    /**
     * Gets the value of the nafPkgProcCategoryCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNafPkgProcCategoryCode() {
        return nafPkgProcCategoryCode;
    }

    /**
     * Sets the value of the nafPkgProcCategoryCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNafPkgProcCategoryCode(String value) {
        this.nafPkgProcCategoryCode = value;
    }

    /**
     * Gets the value of the nafLimitTypeCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNafLimitTypeCode() {
        return nafLimitTypeCode;
    }

    /**
     * Sets the value of the nafLimitTypeCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNafLimitTypeCode(String value) {
        this.nafLimitTypeCode = value;
    }

    /**
     * Gets the value of the nafProductPrice property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNafProductPrice() {
        return nafProductPrice;
    }

    /**
     * Sets the value of the nafProductPrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNafProductPrice(String value) {
        this.nafProductPrice = value;
    }

    /**
     * Gets the value of the compatibleDaccCount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCompatibleDaccCount() {
        return compatibleDaccCount;
    }

    /**
     * Sets the value of the compatibleDaccCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCompatibleDaccCount(String value) {
        this.compatibleDaccCount = value;
    }

    /**
     * Gets the value of the compatibleDaccList property.
     * 
     * @return
     *     possible object is
     *     {@link CompatibleDaccList }
     *     
     */
    public CompatibleDaccList getCompatibleDaccList() {
        return compatibleDaccList;
    }

    /**
     * Sets the value of the compatibleDaccList property.
     * 
     * @param value
     *     allowed object is
     *     {@link CompatibleDaccList }
     *     
     */
    public void setCompatibleDaccList(CompatibleDaccList value) {
        this.compatibleDaccList = value;
    }

}
