//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.13 at 01:37:28 PM EDT 
//


package com.vzwcorp.pricinglab.vo.dvs.nbs;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PlanInfoList complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PlanInfoList">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="planInfoItem" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="planGridIndicator" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="planId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="planDescription" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="planComponentType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="planListPrice" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="planPromotion1Description" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="planPromotion1Discount" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="planPromotion2Description" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="planPromotion2Discount" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="planPromotion3Description" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="planPromotion3Discount" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="planNetAccess" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="planAllowanceList" type="{}ProrateCalcAllowanceInfoList" minOccurs="0"/>
 *                   &lt;element name="planRateList" type="{}RateInfoList" minOccurs="0"/>
 *                   &lt;element name="planProratedInfo" type="{}PlanProratedInfo" minOccurs="0"/>
 *                   &lt;element name="planDragonIndicator" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PlanInfoList", propOrder = {
    "planInfoItem"
})
public class PlanInfoList {

    protected List<PlanInfoList.PlanInfoItem> planInfoItem;

    /**
     * Gets the value of the planInfoItem property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the planInfoItem property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPlanInfoItem().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PlanInfoList.PlanInfoItem }
     * 
     * 
     */
    public List<PlanInfoList.PlanInfoItem> getPlanInfoItem() {
        if (planInfoItem == null) {
            planInfoItem = new ArrayList<PlanInfoList.PlanInfoItem>();
        }
        return this.planInfoItem;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="planGridIndicator" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="planId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="planDescription" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="planComponentType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="planListPrice" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="planPromotion1Description" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="planPromotion1Discount" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="planPromotion2Description" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="planPromotion2Discount" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="planPromotion3Description" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="planPromotion3Discount" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="planNetAccess" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="planAllowanceList" type="{}ProrateCalcAllowanceInfoList" minOccurs="0"/>
     *         &lt;element name="planRateList" type="{}RateInfoList" minOccurs="0"/>
     *         &lt;element name="planProratedInfo" type="{}PlanProratedInfo" minOccurs="0"/>
     *         &lt;element name="planDragonIndicator" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "planGridIndicator",
        "planId",
        "planDescription",
        "planComponentType",
        "planListPrice",
        "planPromotion1Description",
        "planPromotion1Discount",
        "planPromotion2Description",
        "planPromotion2Discount",
        "planPromotion3Description",
        "planPromotion3Discount",
        "planNetAccess",
        "planAllowanceList",
        "planRateList",
        "planProratedInfo",
        "planDragonIndicator"
    })
    public static class PlanInfoItem {

        protected String planGridIndicator;
        protected String planId;
        protected String planDescription;
        protected String planComponentType;
        protected String planListPrice;
        protected String planPromotion1Description;
        protected String planPromotion1Discount;
        protected String planPromotion2Description;
        protected String planPromotion2Discount;
        protected String planPromotion3Description;
        protected String planPromotion3Discount;
        protected String planNetAccess;
        protected ProrateCalcAllowanceInfoList planAllowanceList;
        protected RateInfoList planRateList;
        protected PlanProratedInfo planProratedInfo;
        protected String planDragonIndicator;

        /**
         * Gets the value of the planGridIndicator property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPlanGridIndicator() {
            return planGridIndicator;
        }

        /**
         * Sets the value of the planGridIndicator property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPlanGridIndicator(String value) {
            this.planGridIndicator = value;
        }

        /**
         * Gets the value of the planId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPlanId() {
            return planId;
        }

        /**
         * Sets the value of the planId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPlanId(String value) {
            this.planId = value;
        }

        /**
         * Gets the value of the planDescription property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPlanDescription() {
            return planDescription;
        }

        /**
         * Sets the value of the planDescription property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPlanDescription(String value) {
            this.planDescription = value;
        }

        /**
         * Gets the value of the planComponentType property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPlanComponentType() {
            return planComponentType;
        }

        /**
         * Sets the value of the planComponentType property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPlanComponentType(String value) {
            this.planComponentType = value;
        }

        /**
         * Gets the value of the planListPrice property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPlanListPrice() {
            return planListPrice;
        }

        /**
         * Sets the value of the planListPrice property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPlanListPrice(String value) {
            this.planListPrice = value;
        }

        /**
         * Gets the value of the planPromotion1Description property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPlanPromotion1Description() {
            return planPromotion1Description;
        }

        /**
         * Sets the value of the planPromotion1Description property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPlanPromotion1Description(String value) {
            this.planPromotion1Description = value;
        }

        /**
         * Gets the value of the planPromotion1Discount property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPlanPromotion1Discount() {
            return planPromotion1Discount;
        }

        /**
         * Sets the value of the planPromotion1Discount property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPlanPromotion1Discount(String value) {
            this.planPromotion1Discount = value;
        }

        /**
         * Gets the value of the planPromotion2Description property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPlanPromotion2Description() {
            return planPromotion2Description;
        }

        /**
         * Sets the value of the planPromotion2Description property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPlanPromotion2Description(String value) {
            this.planPromotion2Description = value;
        }

        /**
         * Gets the value of the planPromotion2Discount property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPlanPromotion2Discount() {
            return planPromotion2Discount;
        }

        /**
         * Sets the value of the planPromotion2Discount property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPlanPromotion2Discount(String value) {
            this.planPromotion2Discount = value;
        }

        /**
         * Gets the value of the planPromotion3Description property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPlanPromotion3Description() {
            return planPromotion3Description;
        }

        /**
         * Sets the value of the planPromotion3Description property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPlanPromotion3Description(String value) {
            this.planPromotion3Description = value;
        }

        /**
         * Gets the value of the planPromotion3Discount property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPlanPromotion3Discount() {
            return planPromotion3Discount;
        }

        /**
         * Sets the value of the planPromotion3Discount property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPlanPromotion3Discount(String value) {
            this.planPromotion3Discount = value;
        }

        /**
         * Gets the value of the planNetAccess property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPlanNetAccess() {
            return planNetAccess;
        }

        /**
         * Sets the value of the planNetAccess property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPlanNetAccess(String value) {
            this.planNetAccess = value;
        }

        /**
         * Gets the value of the planAllowanceList property.
         * 
         * @return
         *     possible object is
         *     {@link ProrateCalcAllowanceInfoList }
         *     
         */
        public ProrateCalcAllowanceInfoList getPlanAllowanceList() {
            return planAllowanceList;
        }

        /**
         * Sets the value of the planAllowanceList property.
         * 
         * @param value
         *     allowed object is
         *     {@link ProrateCalcAllowanceInfoList }
         *     
         */
        public void setPlanAllowanceList(ProrateCalcAllowanceInfoList value) {
            this.planAllowanceList = value;
        }

        /**
         * Gets the value of the planRateList property.
         * 
         * @return
         *     possible object is
         *     {@link RateInfoList }
         *     
         */
        public RateInfoList getPlanRateList() {
            return planRateList;
        }

        /**
         * Sets the value of the planRateList property.
         * 
         * @param value
         *     allowed object is
         *     {@link RateInfoList }
         *     
         */
        public void setPlanRateList(RateInfoList value) {
            this.planRateList = value;
        }

        /**
         * Gets the value of the planProratedInfo property.
         * 
         * @return
         *     possible object is
         *     {@link PlanProratedInfo }
         *     
         */
        public PlanProratedInfo getPlanProratedInfo() {
            return planProratedInfo;
        }

        /**
         * Sets the value of the planProratedInfo property.
         * 
         * @param value
         *     allowed object is
         *     {@link PlanProratedInfo }
         *     
         */
        public void setPlanProratedInfo(PlanProratedInfo value) {
            this.planProratedInfo = value;
        }

        /**
         * Gets the value of the planDragonIndicator property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPlanDragonIndicator() {
            return planDragonIndicator;
        }

        /**
         * Sets the value of the planDragonIndicator property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPlanDragonIndicator(String value) {
            this.planDragonIndicator = value;
        }

    }

}
