//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.13 at 01:37:28 PM EDT 
//


package com.vzwcorp.pricinglab.vo.dvs.nbs;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ProrateCalcAllowanceInfoList complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ProrateCalcAllowanceInfoList">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="allowanceInfoItem" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="allowanceOfferId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="allowanceDescription" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="allowance" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="allowanceUnitOfMeasure" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="allowanceUnlimitedIndicator" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="allowanceTypeCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="allowanceSubTypeCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="proratedAllowance" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ProrateCalcAllowanceInfoList", propOrder = {
    "allowanceInfoItem"
})
public class ProrateCalcAllowanceInfoList {

    protected List<ProrateCalcAllowanceInfoList.AllowanceInfoItem> allowanceInfoItem;

    /**
     * Gets the value of the allowanceInfoItem property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the allowanceInfoItem property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAllowanceInfoItem().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ProrateCalcAllowanceInfoList.AllowanceInfoItem }
     * 
     * 
     */
    public List<ProrateCalcAllowanceInfoList.AllowanceInfoItem> getAllowanceInfoItem() {
        if (allowanceInfoItem == null) {
            allowanceInfoItem = new ArrayList<ProrateCalcAllowanceInfoList.AllowanceInfoItem>();
        }
        return this.allowanceInfoItem;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="allowanceOfferId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="allowanceDescription" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="allowance" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="allowanceUnitOfMeasure" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="allowanceUnlimitedIndicator" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="allowanceTypeCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="allowanceSubTypeCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="proratedAllowance" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "allowanceOfferId",
        "allowanceDescription",
        "allowance",
        "allowanceUnitOfMeasure",
        "allowanceUnlimitedIndicator",
        "allowanceTypeCode",
        "allowanceSubTypeCode",
        "proratedAllowance"
    })
    public static class AllowanceInfoItem {

        protected String allowanceOfferId;
        protected String allowanceDescription;
        protected String allowance;
        protected String allowanceUnitOfMeasure;
        protected String allowanceUnlimitedIndicator;
        protected String allowanceTypeCode;
        protected String allowanceSubTypeCode;
        protected String proratedAllowance;

        /**
         * Gets the value of the allowanceOfferId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAllowanceOfferId() {
            return allowanceOfferId;
        }

        /**
         * Sets the value of the allowanceOfferId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAllowanceOfferId(String value) {
            this.allowanceOfferId = value;
        }

        /**
         * Gets the value of the allowanceDescription property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAllowanceDescription() {
            return allowanceDescription;
        }

        /**
         * Sets the value of the allowanceDescription property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAllowanceDescription(String value) {
            this.allowanceDescription = value;
        }

        /**
         * Gets the value of the allowance property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAllowance() {
            return allowance;
        }

        /**
         * Sets the value of the allowance property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAllowance(String value) {
            this.allowance = value;
        }

        /**
         * Gets the value of the allowanceUnitOfMeasure property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAllowanceUnitOfMeasure() {
            return allowanceUnitOfMeasure;
        }

        /**
         * Sets the value of the allowanceUnitOfMeasure property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAllowanceUnitOfMeasure(String value) {
            this.allowanceUnitOfMeasure = value;
        }

        /**
         * Gets the value of the allowanceUnlimitedIndicator property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAllowanceUnlimitedIndicator() {
            return allowanceUnlimitedIndicator;
        }

        /**
         * Sets the value of the allowanceUnlimitedIndicator property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAllowanceUnlimitedIndicator(String value) {
            this.allowanceUnlimitedIndicator = value;
        }

        /**
         * Gets the value of the allowanceTypeCode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAllowanceTypeCode() {
            return allowanceTypeCode;
        }

        /**
         * Sets the value of the allowanceTypeCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAllowanceTypeCode(String value) {
            this.allowanceTypeCode = value;
        }

        /**
         * Gets the value of the allowanceSubTypeCode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAllowanceSubTypeCode() {
            return allowanceSubTypeCode;
        }

        /**
         * Sets the value of the allowanceSubTypeCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAllowanceSubTypeCode(String value) {
            this.allowanceSubTypeCode = value;
        }

        /**
         * Gets the value of the proratedAllowance property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getProratedAllowance() {
            return proratedAllowance;
        }

        /**
         * Sets the value of the proratedAllowance property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setProratedAllowance(String value) {
            this.proratedAllowance = value;
        }

    }

}
