//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.13 at 01:37:28 PM EDT 
//


package com.vzwcorp.pricinglab.vo.dvs.nbs;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}serviceError" minOccurs="0"/>
 *         &lt;element name="productOfferListCount" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element ref="{}listOfProductCorrelation" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "serviceError",
    "productOfferListCount",
    "listOfProductCorrelation"
})
@XmlRootElement(name = "retrieveProduct_byCorrelationID")
public class RetrieveProductByCorrelationID {

    protected ServiceError serviceError;
    protected String productOfferListCount;
    protected ListOfProductCorrelation listOfProductCorrelation;

    /**
     * Gets the value of the serviceError property.
     * 
     * @return
     *     possible object is
     *     {@link ServiceError }
     *     
     */
    public ServiceError getServiceError() {
        return serviceError;
    }

    /**
     * Sets the value of the serviceError property.
     * 
     * @param value
     *     allowed object is
     *     {@link ServiceError }
     *     
     */
    public void setServiceError(ServiceError value) {
        this.serviceError = value;
    }

    /**
     * Gets the value of the productOfferListCount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductOfferListCount() {
        return productOfferListCount;
    }

    /**
     * Sets the value of the productOfferListCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductOfferListCount(String value) {
        this.productOfferListCount = value;
    }

    /**
     * Gets the value of the listOfProductCorrelation property.
     * 
     * @return
     *     possible object is
     *     {@link ListOfProductCorrelation }
     *     
     */
    public ListOfProductCorrelation getListOfProductCorrelation() {
        return listOfProductCorrelation;
    }

    /**
     * Sets the value of the listOfProductCorrelation property.
     * 
     * @param value
     *     allowed object is
     *     {@link ListOfProductCorrelation }
     *     
     */
    public void setListOfProductCorrelation(ListOfProductCorrelation value) {
        this.listOfProductCorrelation = value;
    }

}
