//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.13 at 01:37:28 PM EDT 
//


package com.vzwcorp.pricinglab.vo.dvs.nbs;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}subServiceName"/>
 *         &lt;element name="partialBillRequestIndicator" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="performLineValidation" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="calculateOccsIndicator" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element ref="{}createOrderLineItemList" minOccurs="0"/>
 *         &lt;element name="orderNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="lorNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="emailSuppressIndicator" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="emailAddress1" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="emailAddress2" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="accountLevelTransactionType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "subServiceName",
    "partialBillRequestIndicator",
    "performLineValidation",
    "calculateOccsIndicator",
    "createOrderLineItemList",
    "orderNumber",
    "lorNumber",
    "emailSuppressIndicator",
    "emailAddress1",
    "emailAddress2",
    "accountLevelTransactionType"
})
@XmlRootElement(name = "serviceRequest")
public class ServiceRequest {

    @XmlElement(required = true)
    protected String subServiceName;
    protected String partialBillRequestIndicator;
    protected String performLineValidation;
    protected String calculateOccsIndicator;
    protected CreateOrderLineItemList createOrderLineItemList;
    protected String orderNumber;
    protected String lorNumber;
    protected String emailSuppressIndicator;
    protected String emailAddress1;
    protected String emailAddress2;
    protected String accountLevelTransactionType;

    /**
     * Gets the value of the subServiceName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubServiceName() {
        return subServiceName;
    }

    /**
     * Sets the value of the subServiceName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubServiceName(String value) {
        this.subServiceName = value;
    }

    /**
     * Gets the value of the partialBillRequestIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPartialBillRequestIndicator() {
        return partialBillRequestIndicator;
    }

    /**
     * Sets the value of the partialBillRequestIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPartialBillRequestIndicator(String value) {
        this.partialBillRequestIndicator = value;
    }

    /**
     * Gets the value of the performLineValidation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPerformLineValidation() {
        return performLineValidation;
    }

    /**
     * Sets the value of the performLineValidation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPerformLineValidation(String value) {
        this.performLineValidation = value;
    }

    /**
     * Gets the value of the calculateOccsIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCalculateOccsIndicator() {
        return calculateOccsIndicator;
    }

    /**
     * Sets the value of the calculateOccsIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCalculateOccsIndicator(String value) {
        this.calculateOccsIndicator = value;
    }

    /**
     * Gets the value of the createOrderLineItemList property.
     * 
     * @return
     *     possible object is
     *     {@link CreateOrderLineItemList }
     *     
     */
    public CreateOrderLineItemList getCreateOrderLineItemList() {
        return createOrderLineItemList;
    }

    /**
     * Sets the value of the createOrderLineItemList property.
     * 
     * @param value
     *     allowed object is
     *     {@link CreateOrderLineItemList }
     *     
     */
    public void setCreateOrderLineItemList(CreateOrderLineItemList value) {
        this.createOrderLineItemList = value;
    }

    /**
     * Gets the value of the orderNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrderNumber() {
        return orderNumber;
    }

    /**
     * Sets the value of the orderNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrderNumber(String value) {
        this.orderNumber = value;
    }

    /**
     * Gets the value of the lorNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLorNumber() {
        return lorNumber;
    }

    /**
     * Sets the value of the lorNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLorNumber(String value) {
        this.lorNumber = value;
    }

    /**
     * Gets the value of the emailSuppressIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmailSuppressIndicator() {
        return emailSuppressIndicator;
    }

    /**
     * Sets the value of the emailSuppressIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmailSuppressIndicator(String value) {
        this.emailSuppressIndicator = value;
    }

    /**
     * Gets the value of the emailAddress1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmailAddress1() {
        return emailAddress1;
    }

    /**
     * Sets the value of the emailAddress1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmailAddress1(String value) {
        this.emailAddress1 = value;
    }

    /**
     * Gets the value of the emailAddress2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmailAddress2() {
        return emailAddress2;
    }

    /**
     * Sets the value of the emailAddress2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmailAddress2(String value) {
        this.emailAddress2 = value;
    }

    /**
     * Gets the value of the accountLevelTransactionType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccountLevelTransactionType() {
        return accountLevelTransactionType;
    }

    /**
     * Sets the value of the accountLevelTransactionType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccountLevelTransactionType(String value) {
        this.accountLevelTransactionType = value;
    }

}
