//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.13 at 01:37:28 PM EDT 
//


package com.vzwcorp.pricinglab.vo.dvs.nbs;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ServiceProductOfferInfoList complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ServiceProductOfferInfoList">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="serviceProductOfferInfoItem" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="productGridIndicator" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="productId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="productDescription" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="productOfferTypeCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="productActionIndicator" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="productUniqueId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="productLevelCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="productReinstateIndicator" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="productOfferEffectiveDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="productOfferEndDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="productNewChargeAmount" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="productCurrentChargeAmount" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="productPreviousChargeAmount" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="productNewChargeNetAmount" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="productCurrentChargeNetAmount" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="productPreviousChargeNetAmount" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="albDiscountListCount" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="albDiscountList" type="{}AlbDiscountList" minOccurs="0"/>
 *                   &lt;element name="albAllowanceListCount" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="albAllowanceList" type="{}AlbAllowanceList" minOccurs="0"/>
 *                   &lt;element name="servicePeriodIndicator" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="spoAdvancedIndicator" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ServiceProductOfferInfoList", propOrder = {
    "serviceProductOfferInfoItem"
})
public class ServiceProductOfferInfoList {

    protected List<ServiceProductOfferInfoList.ServiceProductOfferInfoItem> serviceProductOfferInfoItem;

    /**
     * Gets the value of the serviceProductOfferInfoItem property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the serviceProductOfferInfoItem property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getServiceProductOfferInfoItem().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ServiceProductOfferInfoList.ServiceProductOfferInfoItem }
     * 
     * 
     */
    public List<ServiceProductOfferInfoList.ServiceProductOfferInfoItem> getServiceProductOfferInfoItem() {
        if (serviceProductOfferInfoItem == null) {
            serviceProductOfferInfoItem = new ArrayList<ServiceProductOfferInfoList.ServiceProductOfferInfoItem>();
        }
        return this.serviceProductOfferInfoItem;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="productGridIndicator" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="productId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="productDescription" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="productOfferTypeCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="productActionIndicator" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="productUniqueId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="productLevelCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="productReinstateIndicator" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="productOfferEffectiveDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="productOfferEndDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="productNewChargeAmount" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="productCurrentChargeAmount" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="productPreviousChargeAmount" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="productNewChargeNetAmount" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="productCurrentChargeNetAmount" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="productPreviousChargeNetAmount" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="albDiscountListCount" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="albDiscountList" type="{}AlbDiscountList" minOccurs="0"/>
     *         &lt;element name="albAllowanceListCount" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="albAllowanceList" type="{}AlbAllowanceList" minOccurs="0"/>
     *         &lt;element name="servicePeriodIndicator" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="spoAdvancedIndicator" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "productGridIndicator",
        "productId",
        "productDescription",
        "productOfferTypeCode",
        "productActionIndicator",
        "productUniqueId",
        "productLevelCode",
        "productReinstateIndicator",
        "productOfferEffectiveDate",
        "productOfferEndDate",
        "productNewChargeAmount",
        "productCurrentChargeAmount",
        "productPreviousChargeAmount",
        "productNewChargeNetAmount",
        "productCurrentChargeNetAmount",
        "productPreviousChargeNetAmount",
        "albDiscountListCount",
        "albDiscountList",
        "albAllowanceListCount",
        "albAllowanceList",
        "servicePeriodIndicator",
        "spoAdvancedIndicator"
    })
    public static class ServiceProductOfferInfoItem {

        protected String productGridIndicator;
        protected String productId;
        protected String productDescription;
        protected String productOfferTypeCode;
        protected String productActionIndicator;
        protected String productUniqueId;
        protected String productLevelCode;
        protected String productReinstateIndicator;
        protected String productOfferEffectiveDate;
        protected String productOfferEndDate;
        protected String productNewChargeAmount;
        protected String productCurrentChargeAmount;
        protected String productPreviousChargeAmount;
        protected String productNewChargeNetAmount;
        protected String productCurrentChargeNetAmount;
        protected String productPreviousChargeNetAmount;
        protected String albDiscountListCount;
        protected AlbDiscountList albDiscountList;
        protected String albAllowanceListCount;
        protected AlbAllowanceList albAllowanceList;
        protected String servicePeriodIndicator;
        protected String spoAdvancedIndicator;

        /**
         * Gets the value of the productGridIndicator property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getProductGridIndicator() {
            return productGridIndicator;
        }

        /**
         * Sets the value of the productGridIndicator property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setProductGridIndicator(String value) {
            this.productGridIndicator = value;
        }

        /**
         * Gets the value of the productId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getProductId() {
            return productId;
        }

        /**
         * Sets the value of the productId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setProductId(String value) {
            this.productId = value;
        }

        /**
         * Gets the value of the productDescription property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getProductDescription() {
            return productDescription;
        }

        /**
         * Sets the value of the productDescription property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setProductDescription(String value) {
            this.productDescription = value;
        }

        /**
         * Gets the value of the productOfferTypeCode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getProductOfferTypeCode() {
            return productOfferTypeCode;
        }

        /**
         * Sets the value of the productOfferTypeCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setProductOfferTypeCode(String value) {
            this.productOfferTypeCode = value;
        }

        /**
         * Gets the value of the productActionIndicator property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getProductActionIndicator() {
            return productActionIndicator;
        }

        /**
         * Sets the value of the productActionIndicator property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setProductActionIndicator(String value) {
            this.productActionIndicator = value;
        }

        /**
         * Gets the value of the productUniqueId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getProductUniqueId() {
            return productUniqueId;
        }

        /**
         * Sets the value of the productUniqueId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setProductUniqueId(String value) {
            this.productUniqueId = value;
        }

        /**
         * Gets the value of the productLevelCode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getProductLevelCode() {
            return productLevelCode;
        }

        /**
         * Sets the value of the productLevelCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setProductLevelCode(String value) {
            this.productLevelCode = value;
        }

        /**
         * Gets the value of the productReinstateIndicator property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getProductReinstateIndicator() {
            return productReinstateIndicator;
        }

        /**
         * Sets the value of the productReinstateIndicator property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setProductReinstateIndicator(String value) {
            this.productReinstateIndicator = value;
        }

        /**
         * Gets the value of the productOfferEffectiveDate property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getProductOfferEffectiveDate() {
            return productOfferEffectiveDate;
        }

        /**
         * Sets the value of the productOfferEffectiveDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setProductOfferEffectiveDate(String value) {
            this.productOfferEffectiveDate = value;
        }

        /**
         * Gets the value of the productOfferEndDate property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getProductOfferEndDate() {
            return productOfferEndDate;
        }

        /**
         * Sets the value of the productOfferEndDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setProductOfferEndDate(String value) {
            this.productOfferEndDate = value;
        }

        /**
         * Gets the value of the productNewChargeAmount property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getProductNewChargeAmount() {
            return productNewChargeAmount;
        }

        /**
         * Sets the value of the productNewChargeAmount property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setProductNewChargeAmount(String value) {
            this.productNewChargeAmount = value;
        }

        /**
         * Gets the value of the productCurrentChargeAmount property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getProductCurrentChargeAmount() {
            return productCurrentChargeAmount;
        }

        /**
         * Sets the value of the productCurrentChargeAmount property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setProductCurrentChargeAmount(String value) {
            this.productCurrentChargeAmount = value;
        }

        /**
         * Gets the value of the productPreviousChargeAmount property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getProductPreviousChargeAmount() {
            return productPreviousChargeAmount;
        }

        /**
         * Sets the value of the productPreviousChargeAmount property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setProductPreviousChargeAmount(String value) {
            this.productPreviousChargeAmount = value;
        }

        /**
         * Gets the value of the productNewChargeNetAmount property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getProductNewChargeNetAmount() {
            return productNewChargeNetAmount;
        }

        /**
         * Sets the value of the productNewChargeNetAmount property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setProductNewChargeNetAmount(String value) {
            this.productNewChargeNetAmount = value;
        }

        /**
         * Gets the value of the productCurrentChargeNetAmount property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getProductCurrentChargeNetAmount() {
            return productCurrentChargeNetAmount;
        }

        /**
         * Sets the value of the productCurrentChargeNetAmount property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setProductCurrentChargeNetAmount(String value) {
            this.productCurrentChargeNetAmount = value;
        }

        /**
         * Gets the value of the productPreviousChargeNetAmount property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getProductPreviousChargeNetAmount() {
            return productPreviousChargeNetAmount;
        }

        /**
         * Sets the value of the productPreviousChargeNetAmount property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setProductPreviousChargeNetAmount(String value) {
            this.productPreviousChargeNetAmount = value;
        }

        /**
         * Gets the value of the albDiscountListCount property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAlbDiscountListCount() {
            return albDiscountListCount;
        }

        /**
         * Sets the value of the albDiscountListCount property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAlbDiscountListCount(String value) {
            this.albDiscountListCount = value;
        }

        /**
         * Gets the value of the albDiscountList property.
         * 
         * @return
         *     possible object is
         *     {@link AlbDiscountList }
         *     
         */
        public AlbDiscountList getAlbDiscountList() {
            return albDiscountList;
        }

        /**
         * Sets the value of the albDiscountList property.
         * 
         * @param value
         *     allowed object is
         *     {@link AlbDiscountList }
         *     
         */
        public void setAlbDiscountList(AlbDiscountList value) {
            this.albDiscountList = value;
        }

        /**
         * Gets the value of the albAllowanceListCount property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAlbAllowanceListCount() {
            return albAllowanceListCount;
        }

        /**
         * Sets the value of the albAllowanceListCount property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAlbAllowanceListCount(String value) {
            this.albAllowanceListCount = value;
        }

        /**
         * Gets the value of the albAllowanceList property.
         * 
         * @return
         *     possible object is
         *     {@link AlbAllowanceList }
         *     
         */
        public AlbAllowanceList getAlbAllowanceList() {
            return albAllowanceList;
        }

        /**
         * Sets the value of the albAllowanceList property.
         * 
         * @param value
         *     allowed object is
         *     {@link AlbAllowanceList }
         *     
         */
        public void setAlbAllowanceList(AlbAllowanceList value) {
            this.albAllowanceList = value;
        }

        /**
         * Gets the value of the servicePeriodIndicator property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getServicePeriodIndicator() {
            return servicePeriodIndicator;
        }

        /**
         * Sets the value of the servicePeriodIndicator property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setServicePeriodIndicator(String value) {
            this.servicePeriodIndicator = value;
        }

        /**
         * Gets the value of the spoAdvancedIndicator property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSpoAdvancedIndicator() {
            return spoAdvancedIndicator;
        }

        /**
         * Sets the value of the spoAdvancedIndicator property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSpoAdvancedIndicator(String value) {
            this.spoAdvancedIndicator = value;
        }

    }

}
