//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.18 at 05:00:26 PM EDT 
//


package com.vzwcorp.pricinglab.vo.dvs.multilinemixedorderservice;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="programEligibleIndicator" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="mdnInBillToAccountList" type="{}MdnBillToAccountList" minOccurs="0"/>
 *         &lt;element name="ineligibilityInfo" type="{}AcctIneligibilityInfo" minOccurs="0"/>
 *         &lt;element name="totalNumberOfActiveMtns" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="mtnPurchaseLimit" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="acctPurchaseLimit" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="acctUnbilledEqpCharges" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="installmentLoanBalance" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="profileRemainingBTAAmount" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="profileRemainingSpendingLimitAmount" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "programEligibleIndicator",
    "mdnInBillToAccountList",
    "ineligibilityInfo",
    "totalNumberOfActiveMtns",
    "mtnPurchaseLimit",
    "acctPurchaseLimit",
    "acctUnbilledEqpCharges",
    "installmentLoanBalance",
    "profileRemainingBTAAmount",
    "profileRemainingSpendingLimitAmount"
})
@XmlRootElement(name = "billToAccountInfo")
public class BillToAccountInfo {

    protected String programEligibleIndicator;
    protected MdnBillToAccountList mdnInBillToAccountList;
    protected AcctIneligibilityInfo ineligibilityInfo;
    protected String totalNumberOfActiveMtns;
    protected String mtnPurchaseLimit;
    protected String acctPurchaseLimit;
    protected String acctUnbilledEqpCharges;
    protected String installmentLoanBalance;
    protected String profileRemainingBTAAmount;
    protected String profileRemainingSpendingLimitAmount;

    /**
     * Gets the value of the programEligibleIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProgramEligibleIndicator() {
        return programEligibleIndicator;
    }

    /**
     * Sets the value of the programEligibleIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProgramEligibleIndicator(String value) {
        this.programEligibleIndicator = value;
    }

    /**
     * Gets the value of the mdnInBillToAccountList property.
     * 
     * @return
     *     possible object is
     *     {@link MdnBillToAccountList }
     *     
     */
    public MdnBillToAccountList getMdnInBillToAccountList() {
        return mdnInBillToAccountList;
    }

    /**
     * Sets the value of the mdnInBillToAccountList property.
     * 
     * @param value
     *     allowed object is
     *     {@link MdnBillToAccountList }
     *     
     */
    public void setMdnInBillToAccountList(MdnBillToAccountList value) {
        this.mdnInBillToAccountList = value;
    }

    /**
     * Gets the value of the ineligibilityInfo property.
     * 
     * @return
     *     possible object is
     *     {@link AcctIneligibilityInfo }
     *     
     */
    public AcctIneligibilityInfo getIneligibilityInfo() {
        return ineligibilityInfo;
    }

    /**
     * Sets the value of the ineligibilityInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link AcctIneligibilityInfo }
     *     
     */
    public void setIneligibilityInfo(AcctIneligibilityInfo value) {
        this.ineligibilityInfo = value;
    }

    /**
     * Gets the value of the totalNumberOfActiveMtns property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTotalNumberOfActiveMtns() {
        return totalNumberOfActiveMtns;
    }

    /**
     * Sets the value of the totalNumberOfActiveMtns property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTotalNumberOfActiveMtns(String value) {
        this.totalNumberOfActiveMtns = value;
    }

    /**
     * Gets the value of the mtnPurchaseLimit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMtnPurchaseLimit() {
        return mtnPurchaseLimit;
    }

    /**
     * Sets the value of the mtnPurchaseLimit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMtnPurchaseLimit(String value) {
        this.mtnPurchaseLimit = value;
    }

    /**
     * Gets the value of the acctPurchaseLimit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAcctPurchaseLimit() {
        return acctPurchaseLimit;
    }

    /**
     * Sets the value of the acctPurchaseLimit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAcctPurchaseLimit(String value) {
        this.acctPurchaseLimit = value;
    }

    /**
     * Gets the value of the acctUnbilledEqpCharges property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAcctUnbilledEqpCharges() {
        return acctUnbilledEqpCharges;
    }

    /**
     * Sets the value of the acctUnbilledEqpCharges property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAcctUnbilledEqpCharges(String value) {
        this.acctUnbilledEqpCharges = value;
    }

    /**
     * Gets the value of the installmentLoanBalance property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInstallmentLoanBalance() {
        return installmentLoanBalance;
    }

    /**
     * Sets the value of the installmentLoanBalance property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInstallmentLoanBalance(String value) {
        this.installmentLoanBalance = value;
    }

    /**
     * Gets the value of the profileRemainingBTAAmount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProfileRemainingBTAAmount() {
        return profileRemainingBTAAmount;
    }

    /**
     * Sets the value of the profileRemainingBTAAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProfileRemainingBTAAmount(String value) {
        this.profileRemainingBTAAmount = value;
    }

    /**
     * Gets the value of the profileRemainingSpendingLimitAmount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProfileRemainingSpendingLimitAmount() {
        return profileRemainingSpendingLimitAmount;
    }

    /**
     * Sets the value of the profileRemainingSpendingLimitAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProfileRemainingSpendingLimitAmount(String value) {
        this.profileRemainingSpendingLimitAmount = value;
    }

}
