//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.08 at 06:17:55 PM EDT 
//


package com.vzwcorp.pricinglab.vo.onemessagerequest;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.vzwcorp.pricinglab.vo.onemessagerequest package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.vzwcorp.pricinglab.vo.onemessagerequest
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link OneMessageRequest }
     * 
     */
    public OneMessageRequest createOneMessageRequest() {
        return new OneMessageRequest();
    }

    /**
     * Create an instance of {@link DataMapType }
     * 
     */
    public DataMapType createDataMapType() {
        return new DataMapType();
    }

    /**
     * Create an instance of {@link TransactionRecordType }
     * 
     */
    public TransactionRecordType createTransactionRecordType() {
        return new TransactionRecordType();
    }

    /**
     * Create an instance of {@link Customer }
     * 
     */
    public Customer createCustomer() {
        return new Customer();
    }

    /**
     * Create an instance of {@link DataMapItemType }
     * 
     */
    public DataMapItemType createDataMapItemType() {
        return new DataMapItemType();
    }

    /**
     * Create an instance of {@link MTNListType }
     * 
     */
    public MTNListType createMTNListType() {
        return new MTNListType();
    }

}
