//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.17 at 01:57:00 PM EDT 
//


package com.vzwcorp.pricinglab.vo.productvalidation;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}subServiceName" minOccurs="0"/>
 *         &lt;element name="custAccountInfo" type="{}CustAccountInfo" minOccurs="0"/>
 *         &lt;element name="mtnInputCount" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="stateIndicator" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element ref="{}mtnList" minOccurs="0"/>
 *         &lt;element name="groupEditIndicator" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="validateAutoAttachSPOIndicator" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="crossInstanceSPOIndicator" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="sourceInstanceIndicator" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="reAssignType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="productOffersCount" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element ref="{}productOffersList" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "subServiceName",
    "custAccountInfo",
    "mtnInputCount",
    "stateIndicator",
    "mtnList",
    "groupEditIndicator",
    "validateAutoAttachSPOIndicator",
    "crossInstanceSPOIndicator",
    "sourceInstanceIndicator",
    "reAssignType",
    "productOffersCount",
    "productOffersList"
})
@XmlRootElement(name = "serviceRequest")
public class ServiceRequest {

    protected String subServiceName;
    protected CustAccountInfo custAccountInfo;
    protected String mtnInputCount;
    protected String stateIndicator;
    protected MtnList mtnList;
    protected String groupEditIndicator;
    protected String validateAutoAttachSPOIndicator;
    protected String crossInstanceSPOIndicator;
    protected String sourceInstanceIndicator;
    protected String reAssignType;
    protected String productOffersCount;
    protected ProductOffersList productOffersList;

    /**
     * Gets the value of the subServiceName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubServiceName() {
        return subServiceName;
    }

    /**
     * Sets the value of the subServiceName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubServiceName(String value) {
        this.subServiceName = value;
    }

    /**
     * Gets the value of the custAccountInfo property.
     * 
     * @return
     *     possible object is
     *     {@link CustAccountInfo }
     *     
     */
    public CustAccountInfo getCustAccountInfo() {
        return custAccountInfo;
    }

    /**
     * Sets the value of the custAccountInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link CustAccountInfo }
     *     
     */
    public void setCustAccountInfo(CustAccountInfo value) {
        this.custAccountInfo = value;
    }

    /**
     * Gets the value of the mtnInputCount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMtnInputCount() {
        return mtnInputCount;
    }

    /**
     * Sets the value of the mtnInputCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMtnInputCount(String value) {
        this.mtnInputCount = value;
    }

    /**
     * Gets the value of the stateIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStateIndicator() {
        return stateIndicator;
    }

    /**
     * Sets the value of the stateIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStateIndicator(String value) {
        this.stateIndicator = value;
    }

    /**
     * Gets the value of the mtnList property.
     * 
     * @return
     *     possible object is
     *     {@link MtnList }
     *     
     */
    public MtnList getMtnList() {
        return mtnList;
    }

    /**
     * Sets the value of the mtnList property.
     * 
     * @param value
     *     allowed object is
     *     {@link MtnList }
     *     
     */
    public void setMtnList(MtnList value) {
        this.mtnList = value;
    }

    /**
     * Gets the value of the groupEditIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGroupEditIndicator() {
        return groupEditIndicator;
    }

    /**
     * Sets the value of the groupEditIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGroupEditIndicator(String value) {
        this.groupEditIndicator = value;
    }

    /**
     * Gets the value of the validateAutoAttachSPOIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValidateAutoAttachSPOIndicator() {
        return validateAutoAttachSPOIndicator;
    }

    /**
     * Sets the value of the validateAutoAttachSPOIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValidateAutoAttachSPOIndicator(String value) {
        this.validateAutoAttachSPOIndicator = value;
    }

    /**
     * Gets the value of the crossInstanceSPOIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCrossInstanceSPOIndicator() {
        return crossInstanceSPOIndicator;
    }

    /**
     * Sets the value of the crossInstanceSPOIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCrossInstanceSPOIndicator(String value) {
        this.crossInstanceSPOIndicator = value;
    }

    /**
     * Gets the value of the sourceInstanceIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSourceInstanceIndicator() {
        return sourceInstanceIndicator;
    }

    /**
     * Sets the value of the sourceInstanceIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSourceInstanceIndicator(String value) {
        this.sourceInstanceIndicator = value;
    }

    /**
     * Gets the value of the reAssignType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReAssignType() {
        return reAssignType;
    }

    /**
     * Sets the value of the reAssignType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReAssignType(String value) {
        this.reAssignType = value;
    }

    /**
     * Gets the value of the productOffersCount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductOffersCount() {
        return productOffersCount;
    }

    /**
     * Sets the value of the productOffersCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductOffersCount(String value) {
        this.productOffersCount = value;
    }

    /**
     * Gets the value of the productOffersList property.
     * 
     * @return
     *     possible object is
     *     {@link ProductOffersList }
     *     
     */
    public ProductOffersList getProductOffersList() {
        return productOffersList;
    }

    /**
     * Sets the value of the productOffersList property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProductOffersList }
     *     
     */
    public void setProductOffersList(ProductOffersList value) {
        this.productOffersList = value;
    }

}
