//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.17 at 01:57:00 PM EDT 
//


package com.vzwcorp.pricinglab.vo.productvalidation;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="accountLevelProductOffersCount" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element ref="{}accountLevelProductOffers" minOccurs="0"/>
 *         &lt;element name="mtnCount" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element ref="{}mtnOutputList" minOccurs="0"/>
 *         &lt;element name="productOfferReferenceCount" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element ref="{}listOfProductOffersRefData" minOccurs="0"/>
 *         &lt;element name="featureReferenceCount" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element ref="{}featureReferenceList" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "accountLevelProductOffersCount",
    "accountLevelProductOffers",
    "mtnCount",
    "mtnOutputList",
    "productOfferReferenceCount",
    "listOfProductOffersRefData",
    "featureReferenceCount",
    "featureReferenceList"
})
@XmlRootElement(name = "serviceResponse")
public class ServiceResponse {

    protected String accountLevelProductOffersCount;
    protected AccountLevelProductOffers accountLevelProductOffers;
    protected String mtnCount;
    protected MtnOutputList mtnOutputList;
    protected String productOfferReferenceCount;
    protected ListOfProductOffersRefData listOfProductOffersRefData;
    protected String featureReferenceCount;
    protected FeatureReferenceList featureReferenceList;

    /**
     * Gets the value of the accountLevelProductOffersCount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccountLevelProductOffersCount() {
        return accountLevelProductOffersCount;
    }

    /**
     * Sets the value of the accountLevelProductOffersCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccountLevelProductOffersCount(String value) {
        this.accountLevelProductOffersCount = value;
    }

    /**
     * Gets the value of the accountLevelProductOffers property.
     * 
     * @return
     *     possible object is
     *     {@link AccountLevelProductOffers }
     *     
     */
    public AccountLevelProductOffers getAccountLevelProductOffers() {
        return accountLevelProductOffers;
    }

    /**
     * Sets the value of the accountLevelProductOffers property.
     * 
     * @param value
     *     allowed object is
     *     {@link AccountLevelProductOffers }
     *     
     */
    public void setAccountLevelProductOffers(AccountLevelProductOffers value) {
        this.accountLevelProductOffers = value;
    }

    /**
     * Gets the value of the mtnCount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMtnCount() {
        return mtnCount;
    }

    /**
     * Sets the value of the mtnCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMtnCount(String value) {
        this.mtnCount = value;
    }

    /**
     * Gets the value of the mtnOutputList property.
     * 
     * @return
     *     possible object is
     *     {@link MtnOutputList }
     *     
     */
    public MtnOutputList getMtnOutputList() {
        return mtnOutputList;
    }

    /**
     * Sets the value of the mtnOutputList property.
     * 
     * @param value
     *     allowed object is
     *     {@link MtnOutputList }
     *     
     */
    public void setMtnOutputList(MtnOutputList value) {
        this.mtnOutputList = value;
    }

    /**
     * Gets the value of the productOfferReferenceCount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductOfferReferenceCount() {
        return productOfferReferenceCount;
    }

    /**
     * Sets the value of the productOfferReferenceCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductOfferReferenceCount(String value) {
        this.productOfferReferenceCount = value;
    }

    /**
     * Gets the value of the listOfProductOffersRefData property.
     * 
     * @return
     *     possible object is
     *     {@link ListOfProductOffersRefData }
     *     
     */
    public ListOfProductOffersRefData getListOfProductOffersRefData() {
        return listOfProductOffersRefData;
    }

    /**
     * Sets the value of the listOfProductOffersRefData property.
     * 
     * @param value
     *     allowed object is
     *     {@link ListOfProductOffersRefData }
     *     
     */
    public void setListOfProductOffersRefData(ListOfProductOffersRefData value) {
        this.listOfProductOffersRefData = value;
    }

    /**
     * Gets the value of the featureReferenceCount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFeatureReferenceCount() {
        return featureReferenceCount;
    }

    /**
     * Sets the value of the featureReferenceCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFeatureReferenceCount(String value) {
        this.featureReferenceCount = value;
    }

    /**
     * Gets the value of the featureReferenceList property.
     * 
     * @return
     *     possible object is
     *     {@link FeatureReferenceList }
     *     
     */
    public FeatureReferenceList getFeatureReferenceList() {
        return featureReferenceList;
    }

    /**
     * Sets the value of the featureReferenceList property.
     * 
     * @param value
     *     allowed object is
     *     {@link FeatureReferenceList }
     *     
     */
    public void setFeatureReferenceList(FeatureReferenceList value) {
        this.featureReferenceList = value;
    }

}
