//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.20 at 12:05:21 PM EDT 
//


package com.vzwcorp.pricinglab.vo.pounddata;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DataRateGroupInfo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DataRateGroupInfo">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="groupDescription" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="groupAllowanceQuantity" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="dataUsed" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="dataUsedUnitOfMeasure" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="groupCost" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="mdnSharedUsage" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="mdnSharedCost" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DataRateGroupInfo", propOrder = {
    "groupDescription",
    "groupAllowanceQuantity",
    "dataUsed",
    "dataUsedUnitOfMeasure",
    "groupCost",
    "mdnSharedUsage",
    "mdnSharedCost"
})
public class DataRateGroupInfo {

    protected String groupDescription;
    protected String groupAllowanceQuantity;
    protected String dataUsed;
    protected String dataUsedUnitOfMeasure;
    protected String groupCost;
    protected String mdnSharedUsage;
    protected String mdnSharedCost;

    /**
     * Gets the value of the groupDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGroupDescription() {
        return groupDescription;
    }

    /**
     * Sets the value of the groupDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGroupDescription(String value) {
        this.groupDescription = value;
    }

    /**
     * Gets the value of the groupAllowanceQuantity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGroupAllowanceQuantity() {
        return groupAllowanceQuantity;
    }

    /**
     * Sets the value of the groupAllowanceQuantity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGroupAllowanceQuantity(String value) {
        this.groupAllowanceQuantity = value;
    }

    /**
     * Gets the value of the dataUsed property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDataUsed() {
        return dataUsed;
    }

    /**
     * Sets the value of the dataUsed property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDataUsed(String value) {
        this.dataUsed = value;
    }

    /**
     * Gets the value of the dataUsedUnitOfMeasure property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDataUsedUnitOfMeasure() {
        return dataUsedUnitOfMeasure;
    }

    /**
     * Sets the value of the dataUsedUnitOfMeasure property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDataUsedUnitOfMeasure(String value) {
        this.dataUsedUnitOfMeasure = value;
    }

    /**
     * Gets the value of the groupCost property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGroupCost() {
        return groupCost;
    }

    /**
     * Sets the value of the groupCost property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGroupCost(String value) {
        this.groupCost = value;
    }

    /**
     * Gets the value of the mdnSharedUsage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMdnSharedUsage() {
        return mdnSharedUsage;
    }

    /**
     * Sets the value of the mdnSharedUsage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMdnSharedUsage(String value) {
        this.mdnSharedUsage = value;
    }

    /**
     * Gets the value of the mdnSharedCost property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMdnSharedCost() {
        return mdnSharedCost;
    }

    /**
     * Sets the value of the mdnSharedCost property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMdnSharedCost(String value) {
        this.mdnSharedCost = value;
    }

}
