//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.20 at 12:05:21 PM EDT 
//


package com.vzwcorp.pricinglab.vo.pounddata;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.vzwcorp.pricinglab.vo.pounddata package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _SubServiceName_QNAME = new QName("", "subServiceName");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.vzwcorp.pricinglab.vo.pounddata
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link OtherMessageAllowanceBarList }
     * 
     */
    public OtherMessageAllowanceBarList createOtherMessageAllowanceBarList() {
        return new OtherMessageAllowanceBarList();
    }

    /**
     * Create an instance of {@link OtherMessageAllowanceBarItem }
     * 
     */
    public OtherMessageAllowanceBarItem createOtherMessageAllowanceBarItem() {
        return new OtherMessageAllowanceBarItem();
    }

    /**
     * Create an instance of {@link ServiceBody }
     * 
     */
    public ServiceBody createServiceBody() {
        return new ServiceBody();
    }

    /**
     * Create an instance of {@link ServiceRequest }
     * 
     */
    public ServiceRequest createServiceRequest() {
        return new ServiceRequest();
    }

    /**
     * Create an instance of {@link SeedInfo }
     * 
     */
    public SeedInfo createSeedInfo() {
        return new SeedInfo();
    }

    /**
     * Create an instance of {@link ServiceResponse }
     * 
     */
    public ServiceResponse createServiceResponse() {
        return new ServiceResponse();
    }

    /**
     * Create an instance of {@link VoiceUsageInfo }
     * 
     */
    public VoiceUsageInfo createVoiceUsageInfo() {
        return new VoiceUsageInfo();
    }

    /**
     * Create an instance of {@link MessageUsageInfo }
     * 
     */
    public MessageUsageInfo createMessageUsageInfo() {
        return new MessageUsageInfo();
    }

    /**
     * Create an instance of {@link DataUsageInfo }
     * 
     */
    public DataUsageInfo createDataUsageInfo() {
        return new DataUsageInfo();
    }

    /**
     * Create an instance of {@link BillCycleDateInfo }
     * 
     */
    public BillCycleDateInfo createBillCycleDateInfo() {
        return new BillCycleDateInfo();
    }

    /**
     * Create an instance of {@link OtherVoiceAllowanceBarList }
     * 
     */
    public OtherVoiceAllowanceBarList createOtherVoiceAllowanceBarList() {
        return new OtherVoiceAllowanceBarList();
    }

    /**
     * Create an instance of {@link OtherVoiceAllowanceBarItem }
     * 
     */
    public OtherVoiceAllowanceBarItem createOtherVoiceAllowanceBarItem() {
        return new OtherVoiceAllowanceBarItem();
    }

    /**
     * Create an instance of {@link AllowanceDataItemList }
     * 
     */
    public AllowanceDataItemList createAllowanceDataItemList() {
        return new AllowanceDataItemList();
    }

    /**
     * Create an instance of {@link AllowanceDetails }
     * 
     */
    public AllowanceDetails createAllowanceDetails() {
        return new AllowanceDetails();
    }

    /**
     * Create an instance of {@link DataRateGroupList }
     * 
     */
    public DataRateGroupList createDataRateGroupList() {
        return new DataRateGroupList();
    }

    /**
     * Create an instance of {@link DataRateGroupInfo }
     * 
     */
    public DataRateGroupInfo createDataRateGroupInfo() {
        return new DataRateGroupInfo();
    }

    /**
     * Create an instance of {@link Service }
     * 
     */
    public Service createService() {
        return new Service();
    }

    /**
     * Create an instance of {@link ServiceHeader }
     * 
     */
    public ServiceHeader createServiceHeader() {
        return new ServiceHeader();
    }

    /**
     * Create an instance of {@link AdditionalUsageProductDataItemList }
     * 
     */
    public AdditionalUsageProductDataItemList createAdditionalUsageProductDataItemList() {
        return new AdditionalUsageProductDataItemList();
    }

    /**
     * Create an instance of {@link AdditionalUsageProductDetails }
     * 
     */
    public AdditionalUsageProductDetails createAdditionalUsageProductDetails() {
        return new AdditionalUsageProductDetails();
    }

    /**
     * Create an instance of {@link ShareDataInfo }
     * 
     */
    public ShareDataInfo createShareDataInfo() {
        return new ShareDataInfo();
    }

    /**
     * Create an instance of {@link GlobalMinutesInfo }
     * 
     */
    public GlobalMinutesInfo createGlobalMinutesInfo() {
        return new GlobalMinutesInfo();
    }

    /**
     * Create an instance of {@link Allowances }
     * 
     */
    public Allowances createAllowances() {
        return new Allowances();
    }

    /**
     * Create an instance of {@link DataAllowanceBar }
     * 
     */
    public DataAllowanceBar createDataAllowanceBar() {
        return new DataAllowanceBar();
    }

    /**
     * Create an instance of {@link CarryOverDataAllowances }
     * 
     */
    public CarryOverDataAllowances createCarryOverDataAllowances() {
        return new CarryOverDataAllowances();
    }

    /**
     * Create an instance of {@link MinutesInfo }
     * 
     */
    public MinutesInfo createMinutesInfo() {
        return new MinutesInfo();
    }

    /**
     * Create an instance of {@link GlobalRoamAllOtherFeatures }
     * 
     */
    public GlobalRoamAllOtherFeatures createGlobalRoamAllOtherFeatures() {
        return new GlobalRoamAllOtherFeatures();
    }

    /**
     * Create an instance of {@link GlobalRoamFeatureInfo }
     * 
     */
    public GlobalRoamFeatureInfo createGlobalRoamFeatureInfo() {
        return new GlobalRoamFeatureInfo();
    }

    /**
     * Create an instance of {@link ShareVoiceInfo }
     * 
     */
    public ShareVoiceInfo createShareVoiceInfo() {
        return new ShareVoiceInfo();
    }

    /**
     * Create an instance of {@link SmsInfo }
     * 
     */
    public SmsInfo createSmsInfo() {
        return new SmsInfo();
    }

    /**
     * Create an instance of {@link AdditionalUsageProductList }
     * 
     */
    public AdditionalUsageProductList createAdditionalUsageProductList() {
        return new AdditionalUsageProductList();
    }

    /**
     * Create an instance of {@link VoiceUsageItem }
     * 
     */
    public VoiceUsageItem createVoiceUsageItem() {
        return new VoiceUsageItem();
    }

    /**
     * Create an instance of {@link DataUsageItem }
     * 
     */
    public DataUsageItem createDataUsageItem() {
        return new DataUsageItem();
    }

    /**
     * Create an instance of {@link DataInfo }
     * 
     */
    public DataInfo createDataInfo() {
        return new DataInfo();
    }

    /**
     * Create an instance of {@link MmsInfo }
     * 
     */
    public MmsInfo createMmsInfo() {
        return new MmsInfo();
    }

    /**
     * Create an instance of {@link MessageUsageItem }
     * 
     */
    public MessageUsageItem createMessageUsageItem() {
        return new MessageUsageItem();
    }

    /**
     * Create an instance of {@link VoiceAllowanceBar }
     * 
     */
    public VoiceAllowanceBar createVoiceAllowanceBar() {
        return new VoiceAllowanceBar();
    }

    /**
     * Create an instance of {@link VoiceItemList }
     * 
     */
    public VoiceItemList createVoiceItemList() {
        return new VoiceItemList();
    }

    /**
     * Create an instance of {@link AllowanceItem }
     * 
     */
    public AllowanceItem createAllowanceItem() {
        return new AllowanceItem();
    }

    /**
     * Create an instance of {@link ShareMessageInfo }
     * 
     */
    public ShareMessageInfo createShareMessageInfo() {
        return new ShareMessageInfo();
    }

    /**
     * Create an instance of {@link TextAllowanceBar }
     * 
     */
    public TextAllowanceBar createTextAllowanceBar() {
        return new TextAllowanceBar();
    }

    /**
     * Create an instance of {@link Counter }
     * 
     */
    public Counter createCounter() {
        return new Counter();
    }

    /**
     * Create an instance of {@link CounterList }
     * 
     */
    public CounterList createCounterList() {
        return new CounterList();
    }

    /**
     * Create an instance of {@link MessageAllowanceBarList }
     * 
     */
    public MessageAllowanceBarList createMessageAllowanceBarList() {
        return new MessageAllowanceBarList();
    }

    /**
     * Create an instance of {@link GlobalRoamData }
     * 
     */
    public GlobalRoamData createGlobalRoamData() {
        return new GlobalRoamData();
    }

    /**
     * Create an instance of {@link HotspotInfo }
     * 
     */
    public HotspotInfo createHotspotInfo() {
        return new HotspotInfo();
    }

    /**
     * Create an instance of {@link MessageItemList }
     * 
     */
    public MessageItemList createMessageItemList() {
        return new MessageItemList();
    }

    /**
     * Create an instance of {@link GlobalRoamFeature }
     * 
     */
    public GlobalRoamFeature createGlobalRoamFeature() {
        return new GlobalRoamFeature();
    }

    /**
     * Create an instance of {@link AdditionalUsageProductAllowances }
     * 
     */
    public AdditionalUsageProductAllowances createAdditionalUsageProductAllowances() {
        return new AdditionalUsageProductAllowances();
    }

    /**
     * Create an instance of {@link AllowanceList }
     * 
     */
    public AllowanceList createAllowanceList() {
        return new AllowanceList();
    }

    /**
     * Create an instance of {@link DataItemList }
     * 
     */
    public DataItemList createDataItemList() {
        return new DataItemList();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "subServiceName")
    public JAXBElement<String> createSubServiceName(String value) {
        return new JAXBElement<String>(_SubServiceName_QNAME, String.class, null, value);
    }

}
