//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.20 at 12:05:21 PM EDT 
//


package com.vzwcorp.pricinglab.vo.pounddata;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for OtherVoiceAllowanceBarItem complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OtherVoiceAllowanceBarItem">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="barSequence" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="shareIndicator" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="allowanceTypeCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="barColor" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="barPercent" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="totalUsed" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="totalUsedNoAllowance" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="totalAllowed" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="totalRemaining" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="totalOverAllowance" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="allowanceTypeIndicator" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="allowanceSource" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="serviceProductId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="lastCallDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="lastCallTime" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="warningCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="serviceProductEffectiveDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="serviceProductEndDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OtherVoiceAllowanceBarItem", propOrder = {
    "barSequence",
    "shareIndicator",
    "allowanceTypeCode",
    "barColor",
    "barPercent",
    "totalUsed",
    "totalUsedNoAllowance",
    "totalAllowed",
    "totalRemaining",
    "totalOverAllowance",
    "allowanceTypeIndicator",
    "allowanceSource",
    "serviceProductId",
    "lastCallDate",
    "lastCallTime",
    "warningCode",
    "serviceProductEffectiveDate",
    "serviceProductEndDate"
})
public class OtherVoiceAllowanceBarItem {

    protected String barSequence;
    protected String shareIndicator;
    protected String allowanceTypeCode;
    protected String barColor;
    protected String barPercent;
    protected String totalUsed;
    protected String totalUsedNoAllowance;
    protected String totalAllowed;
    protected String totalRemaining;
    protected String totalOverAllowance;
    protected String allowanceTypeIndicator;
    protected String allowanceSource;
    protected String serviceProductId;
    protected String lastCallDate;
    protected String lastCallTime;
    protected String warningCode;
    protected String serviceProductEffectiveDate;
    protected String serviceProductEndDate;

    /**
     * Gets the value of the barSequence property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBarSequence() {
        return barSequence;
    }

    /**
     * Sets the value of the barSequence property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBarSequence(String value) {
        this.barSequence = value;
    }

    /**
     * Gets the value of the shareIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShareIndicator() {
        return shareIndicator;
    }

    /**
     * Sets the value of the shareIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShareIndicator(String value) {
        this.shareIndicator = value;
    }

    /**
     * Gets the value of the allowanceTypeCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAllowanceTypeCode() {
        return allowanceTypeCode;
    }

    /**
     * Sets the value of the allowanceTypeCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAllowanceTypeCode(String value) {
        this.allowanceTypeCode = value;
    }

    /**
     * Gets the value of the barColor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBarColor() {
        return barColor;
    }

    /**
     * Sets the value of the barColor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBarColor(String value) {
        this.barColor = value;
    }

    /**
     * Gets the value of the barPercent property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBarPercent() {
        return barPercent;
    }

    /**
     * Sets the value of the barPercent property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBarPercent(String value) {
        this.barPercent = value;
    }

    /**
     * Gets the value of the totalUsed property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTotalUsed() {
        return totalUsed;
    }

    /**
     * Sets the value of the totalUsed property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTotalUsed(String value) {
        this.totalUsed = value;
    }

    /**
     * Gets the value of the totalUsedNoAllowance property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTotalUsedNoAllowance() {
        return totalUsedNoAllowance;
    }

    /**
     * Sets the value of the totalUsedNoAllowance property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTotalUsedNoAllowance(String value) {
        this.totalUsedNoAllowance = value;
    }

    /**
     * Gets the value of the totalAllowed property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTotalAllowed() {
        return totalAllowed;
    }

    /**
     * Sets the value of the totalAllowed property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTotalAllowed(String value) {
        this.totalAllowed = value;
    }

    /**
     * Gets the value of the totalRemaining property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTotalRemaining() {
        return totalRemaining;
    }

    /**
     * Sets the value of the totalRemaining property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTotalRemaining(String value) {
        this.totalRemaining = value;
    }

    /**
     * Gets the value of the totalOverAllowance property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTotalOverAllowance() {
        return totalOverAllowance;
    }

    /**
     * Sets the value of the totalOverAllowance property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTotalOverAllowance(String value) {
        this.totalOverAllowance = value;
    }

    /**
     * Gets the value of the allowanceTypeIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAllowanceTypeIndicator() {
        return allowanceTypeIndicator;
    }

    /**
     * Sets the value of the allowanceTypeIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAllowanceTypeIndicator(String value) {
        this.allowanceTypeIndicator = value;
    }

    /**
     * Gets the value of the allowanceSource property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAllowanceSource() {
        return allowanceSource;
    }

    /**
     * Sets the value of the allowanceSource property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAllowanceSource(String value) {
        this.allowanceSource = value;
    }

    /**
     * Gets the value of the serviceProductId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServiceProductId() {
        return serviceProductId;
    }

    /**
     * Sets the value of the serviceProductId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServiceProductId(String value) {
        this.serviceProductId = value;
    }

    /**
     * Gets the value of the lastCallDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastCallDate() {
        return lastCallDate;
    }

    /**
     * Sets the value of the lastCallDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastCallDate(String value) {
        this.lastCallDate = value;
    }

    /**
     * Gets the value of the lastCallTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastCallTime() {
        return lastCallTime;
    }

    /**
     * Sets the value of the lastCallTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastCallTime(String value) {
        this.lastCallTime = value;
    }

    /**
     * Gets the value of the warningCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWarningCode() {
        return warningCode;
    }

    /**
     * Sets the value of the warningCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWarningCode(String value) {
        this.warningCode = value;
    }

    /**
     * Gets the value of the serviceProductEffectiveDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServiceProductEffectiveDate() {
        return serviceProductEffectiveDate;
    }

    /**
     * Sets the value of the serviceProductEffectiveDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServiceProductEffectiveDate(String value) {
        this.serviceProductEffectiveDate = value;
    }

    /**
     * Gets the value of the serviceProductEndDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServiceProductEndDate() {
        return serviceProductEndDate;
    }

    /**
     * Sets the value of the serviceProductEndDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServiceProductEndDate(String value) {
        this.serviceProductEndDate = value;
    }

}
