//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.20 at 04:17:33 PM EDT 
//


package com.vzwcorp.pricinglab.vo.dvs.retrievecustomerprofile;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DataItem complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DataItem">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="mdn" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element ref="{}monthlydataUsageInfoList"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DataItem", propOrder = {
    "mdn",
    "monthlydataUsageInfoList"
})
public class DataItem {

    protected String mdn;
    @XmlElement(required = true)
    protected MonthlydataUsageInfoList monthlydataUsageInfoList;

    /**
     * Gets the value of the mdn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMdn() {
        return mdn;
    }

    /**
     * Sets the value of the mdn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMdn(String value) {
        this.mdn = value;
    }

    /**
     * Gets the value of the monthlydataUsageInfoList property.
     * 
     * @return
     *     possible object is
     *     {@link MonthlydataUsageInfoList }
     *     
     */
    public MonthlydataUsageInfoList getMonthlydataUsageInfoList() {
        return monthlydataUsageInfoList;
    }

    /**
     * Sets the value of the monthlydataUsageInfoList property.
     * 
     * @param value
     *     allowed object is
     *     {@link MonthlydataUsageInfoList }
     *     
     */
    public void setMonthlydataUsageInfoList(MonthlydataUsageInfoList value) {
        this.monthlydataUsageInfoList = value;
    }

}
