//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.20 at 04:17:33 PM EDT 
//


package com.vzwcorp.pricinglab.vo.dvs.retrievecustomerprofile;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for OBPPInfo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OBPPInfo">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="obppPaymentMethod" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="settlementDay" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="obppPaperBillIndicator" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="suspendInd" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="zipCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="billCycleNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="obppStatusIndicator" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="obppEditsInd" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="obppEditIndicator" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="settlementDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ach2DayLimitInd" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="eCustomerIndicator" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="eCustomerDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="singleBillCompanyCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="highUsageSuppressionCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="highUsageSuppressionEffectiveDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="recurringAchEligibility" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="recurringApoEligibility" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="outstandingBalance" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="finalBillIndicator" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="enrollVenueCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="trialProgramIndicator" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="paperlessBillingMostRecentEffectiveTimestamp" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="autoServiceRestoreInd" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="accountLevelBillFormatCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="accountLevelBillFormatDescription" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="paperFreeAutoEnrollDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="paperFreeSuppressionCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="billPrintSuppressionDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="FailedAutoPayIndicator" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="autoPayFailedIndicator" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OBPPInfo", propOrder = {
    "obppPaymentMethod",
    "settlementDay",
    "obppPaperBillIndicator",
    "suspendInd",
    "zipCode",
    "billCycleNumber",
    "obppStatusIndicator",
    "obppEditsInd",
    "obppEditIndicator",
    "settlementDate",
    "ach2DayLimitInd",
    "eCustomerIndicator",
    "eCustomerDate",
    "singleBillCompanyCode",
    "highUsageSuppressionCode",
    "highUsageSuppressionEffectiveDate",
    "recurringAchEligibility",
    "recurringApoEligibility",
    "outstandingBalance",
    "finalBillIndicator",
    "enrollVenueCode",
    "trialProgramIndicator",
    "paperlessBillingMostRecentEffectiveTimestamp",
    "autoServiceRestoreInd",
    "accountLevelBillFormatCode",
    "accountLevelBillFormatDescription",
    "paperFreeAutoEnrollDate",
    "paperFreeSuppressionCode",
    "billPrintSuppressionDate",
    "failedAutoPayIndicator",
    "autoPayFailedIndicator"
})
public class OBPPInfo {

    protected String obppPaymentMethod;
    protected String settlementDay;
    protected String obppPaperBillIndicator;
    protected String suspendInd;
    protected String zipCode;
    protected String billCycleNumber;
    protected String obppStatusIndicator;
    protected List<String> obppEditsInd;
    protected String obppEditIndicator;
    protected String settlementDate;
    protected String ach2DayLimitInd;
    protected String eCustomerIndicator;
    protected String eCustomerDate;
    protected String singleBillCompanyCode;
    protected String highUsageSuppressionCode;
    protected String highUsageSuppressionEffectiveDate;
    protected String recurringAchEligibility;
    protected String recurringApoEligibility;
    protected String outstandingBalance;
    protected String finalBillIndicator;
    protected String enrollVenueCode;
    protected String trialProgramIndicator;
    protected String paperlessBillingMostRecentEffectiveTimestamp;
    protected String autoServiceRestoreInd;
    protected String accountLevelBillFormatCode;
    protected String accountLevelBillFormatDescription;
    protected String paperFreeAutoEnrollDate;
    protected String paperFreeSuppressionCode;
    protected String billPrintSuppressionDate;
    @XmlElement(name = "FailedAutoPayIndicator")
    protected String failedAutoPayIndicator;
    protected String autoPayFailedIndicator;

    /**
     * Gets the value of the obppPaymentMethod property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getObppPaymentMethod() {
        return obppPaymentMethod;
    }

    /**
     * Sets the value of the obppPaymentMethod property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setObppPaymentMethod(String value) {
        this.obppPaymentMethod = value;
    }

    /**
     * Gets the value of the settlementDay property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSettlementDay() {
        return settlementDay;
    }

    /**
     * Sets the value of the settlementDay property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSettlementDay(String value) {
        this.settlementDay = value;
    }

    /**
     * Gets the value of the obppPaperBillIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getObppPaperBillIndicator() {
        return obppPaperBillIndicator;
    }

    /**
     * Sets the value of the obppPaperBillIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setObppPaperBillIndicator(String value) {
        this.obppPaperBillIndicator = value;
    }

    /**
     * Gets the value of the suspendInd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSuspendInd() {
        return suspendInd;
    }

    /**
     * Sets the value of the suspendInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSuspendInd(String value) {
        this.suspendInd = value;
    }

    /**
     * Gets the value of the zipCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getZipCode() {
        return zipCode;
    }

    /**
     * Sets the value of the zipCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setZipCode(String value) {
        this.zipCode = value;
    }

    /**
     * Gets the value of the billCycleNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBillCycleNumber() {
        return billCycleNumber;
    }

    /**
     * Sets the value of the billCycleNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBillCycleNumber(String value) {
        this.billCycleNumber = value;
    }

    /**
     * Gets the value of the obppStatusIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getObppStatusIndicator() {
        return obppStatusIndicator;
    }

    /**
     * Sets the value of the obppStatusIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setObppStatusIndicator(String value) {
        this.obppStatusIndicator = value;
    }

    /**
     * Gets the value of the obppEditsInd property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the obppEditsInd property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getObppEditsInd().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getObppEditsInd() {
        if (obppEditsInd == null) {
            obppEditsInd = new ArrayList<String>();
        }
        return this.obppEditsInd;
    }

    /**
     * Gets the value of the obppEditIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getObppEditIndicator() {
        return obppEditIndicator;
    }

    /**
     * Sets the value of the obppEditIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setObppEditIndicator(String value) {
        this.obppEditIndicator = value;
    }

    /**
     * Gets the value of the settlementDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSettlementDate() {
        return settlementDate;
    }

    /**
     * Sets the value of the settlementDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSettlementDate(String value) {
        this.settlementDate = value;
    }

    /**
     * Gets the value of the ach2DayLimitInd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAch2DayLimitInd() {
        return ach2DayLimitInd;
    }

    /**
     * Sets the value of the ach2DayLimitInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAch2DayLimitInd(String value) {
        this.ach2DayLimitInd = value;
    }

    /**
     * Gets the value of the eCustomerIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getECustomerIndicator() {
        return eCustomerIndicator;
    }

    /**
     * Sets the value of the eCustomerIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setECustomerIndicator(String value) {
        this.eCustomerIndicator = value;
    }

    /**
     * Gets the value of the eCustomerDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getECustomerDate() {
        return eCustomerDate;
    }

    /**
     * Sets the value of the eCustomerDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setECustomerDate(String value) {
        this.eCustomerDate = value;
    }

    /**
     * Gets the value of the singleBillCompanyCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSingleBillCompanyCode() {
        return singleBillCompanyCode;
    }

    /**
     * Sets the value of the singleBillCompanyCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSingleBillCompanyCode(String value) {
        this.singleBillCompanyCode = value;
    }

    /**
     * Gets the value of the highUsageSuppressionCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHighUsageSuppressionCode() {
        return highUsageSuppressionCode;
    }

    /**
     * Sets the value of the highUsageSuppressionCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHighUsageSuppressionCode(String value) {
        this.highUsageSuppressionCode = value;
    }

    /**
     * Gets the value of the highUsageSuppressionEffectiveDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHighUsageSuppressionEffectiveDate() {
        return highUsageSuppressionEffectiveDate;
    }

    /**
     * Sets the value of the highUsageSuppressionEffectiveDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHighUsageSuppressionEffectiveDate(String value) {
        this.highUsageSuppressionEffectiveDate = value;
    }

    /**
     * Gets the value of the recurringAchEligibility property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRecurringAchEligibility() {
        return recurringAchEligibility;
    }

    /**
     * Sets the value of the recurringAchEligibility property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRecurringAchEligibility(String value) {
        this.recurringAchEligibility = value;
    }

    /**
     * Gets the value of the recurringApoEligibility property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRecurringApoEligibility() {
        return recurringApoEligibility;
    }

    /**
     * Sets the value of the recurringApoEligibility property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRecurringApoEligibility(String value) {
        this.recurringApoEligibility = value;
    }

    /**
     * Gets the value of the outstandingBalance property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOutstandingBalance() {
        return outstandingBalance;
    }

    /**
     * Sets the value of the outstandingBalance property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOutstandingBalance(String value) {
        this.outstandingBalance = value;
    }

    /**
     * Gets the value of the finalBillIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFinalBillIndicator() {
        return finalBillIndicator;
    }

    /**
     * Sets the value of the finalBillIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFinalBillIndicator(String value) {
        this.finalBillIndicator = value;
    }

    /**
     * Gets the value of the enrollVenueCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEnrollVenueCode() {
        return enrollVenueCode;
    }

    /**
     * Sets the value of the enrollVenueCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEnrollVenueCode(String value) {
        this.enrollVenueCode = value;
    }

    /**
     * Gets the value of the trialProgramIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTrialProgramIndicator() {
        return trialProgramIndicator;
    }

    /**
     * Sets the value of the trialProgramIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTrialProgramIndicator(String value) {
        this.trialProgramIndicator = value;
    }

    /**
     * Gets the value of the paperlessBillingMostRecentEffectiveTimestamp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPaperlessBillingMostRecentEffectiveTimestamp() {
        return paperlessBillingMostRecentEffectiveTimestamp;
    }

    /**
     * Sets the value of the paperlessBillingMostRecentEffectiveTimestamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPaperlessBillingMostRecentEffectiveTimestamp(String value) {
        this.paperlessBillingMostRecentEffectiveTimestamp = value;
    }

    /**
     * Gets the value of the autoServiceRestoreInd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAutoServiceRestoreInd() {
        return autoServiceRestoreInd;
    }

    /**
     * Sets the value of the autoServiceRestoreInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAutoServiceRestoreInd(String value) {
        this.autoServiceRestoreInd = value;
    }

    /**
     * Gets the value of the accountLevelBillFormatCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccountLevelBillFormatCode() {
        return accountLevelBillFormatCode;
    }

    /**
     * Sets the value of the accountLevelBillFormatCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccountLevelBillFormatCode(String value) {
        this.accountLevelBillFormatCode = value;
    }

    /**
     * Gets the value of the accountLevelBillFormatDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccountLevelBillFormatDescription() {
        return accountLevelBillFormatDescription;
    }

    /**
     * Sets the value of the accountLevelBillFormatDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccountLevelBillFormatDescription(String value) {
        this.accountLevelBillFormatDescription = value;
    }

    /**
     * Gets the value of the paperFreeAutoEnrollDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPaperFreeAutoEnrollDate() {
        return paperFreeAutoEnrollDate;
    }

    /**
     * Sets the value of the paperFreeAutoEnrollDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPaperFreeAutoEnrollDate(String value) {
        this.paperFreeAutoEnrollDate = value;
    }

    /**
     * Gets the value of the paperFreeSuppressionCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPaperFreeSuppressionCode() {
        return paperFreeSuppressionCode;
    }

    /**
     * Sets the value of the paperFreeSuppressionCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPaperFreeSuppressionCode(String value) {
        this.paperFreeSuppressionCode = value;
    }

    /**
     * Gets the value of the billPrintSuppressionDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBillPrintSuppressionDate() {
        return billPrintSuppressionDate;
    }

    /**
     * Sets the value of the billPrintSuppressionDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBillPrintSuppressionDate(String value) {
        this.billPrintSuppressionDate = value;
    }

    /**
     * Gets the value of the failedAutoPayIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFailedAutoPayIndicator() {
        return failedAutoPayIndicator;
    }

    /**
     * Sets the value of the failedAutoPayIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFailedAutoPayIndicator(String value) {
        this.failedAutoPayIndicator = value;
    }

    /**
     * Gets the value of the autoPayFailedIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAutoPayFailedIndicator() {
        return autoPayFailedIndicator;
    }

    /**
     * Sets the value of the autoPayFailedIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAutoPayFailedIndicator(String value) {
        this.autoPayFailedIndicator = value;
    }

}
