//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.31 at 10:31:22 AM EDT 
//


package com.vzwcorp.pricinglab.vo.mcs.ezcheckout;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Details of Account Payment status Details 
 * 
 * <p>Java class for AcctPmtStatDetailsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AcctPmtStatDetailsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.vzw.com/namespaces/scmplus}BlMthdCd" minOccurs="0"/>
 *         &lt;element ref="{http://www.vzw.com/namespaces/scmplus}SettleDay" minOccurs="0"/>
 *         &lt;element ref="{http://www.vzw.com/namespaces/scmplus}APOEffTmstamp" minOccurs="0"/>
 *         &lt;element ref="{http://www.vzw.com/namespaces/scmplus}APOEndTmstamp" minOccurs="0"/>
 *         &lt;element ref="{http://www.vzw.com/namespaces/scmplus}DeEnrollRsnCd" minOccurs="0"/>
 *         &lt;element ref="{http://www.vzw.com/namespaces/scmplus}BadPayEndDt" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AcctPmtStatDetailsType", propOrder = {
    "blMthdCd",
    "settleDay",
    "apoEffTmstamp",
    "apoEndTmstamp",
    "deEnrollRsnCd",
    "badPayEndDt"
})
public class AcctPmtStatDetailsType {

    @XmlElement(name = "BlMthdCd")
    protected String blMthdCd;
    @XmlElement(name = "SettleDay")
    protected BigInteger settleDay;
    @XmlElement(name = "APOEffTmstamp")
    protected String apoEffTmstamp;
    @XmlElement(name = "APOEndTmstamp")
    protected String apoEndTmstamp;
    @XmlElement(name = "DeEnrollRsnCd")
    protected String deEnrollRsnCd;
    @XmlElement(name = "BadPayEndDt")
    protected String badPayEndDt;

    /**
     * Gets the value of the blMthdCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBlMthdCd() {
        return blMthdCd;
    }

    /**
     * Sets the value of the blMthdCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBlMthdCd(String value) {
        this.blMthdCd = value;
    }

    /**
     * Gets the value of the settleDay property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSettleDay() {
        return settleDay;
    }

    /**
     * Sets the value of the settleDay property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSettleDay(BigInteger value) {
        this.settleDay = value;
    }

    /**
     * Gets the value of the apoEffTmstamp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAPOEffTmstamp() {
        return apoEffTmstamp;
    }

    /**
     * Sets the value of the apoEffTmstamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAPOEffTmstamp(String value) {
        this.apoEffTmstamp = value;
    }

    /**
     * Gets the value of the apoEndTmstamp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAPOEndTmstamp() {
        return apoEndTmstamp;
    }

    /**
     * Sets the value of the apoEndTmstamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAPOEndTmstamp(String value) {
        this.apoEndTmstamp = value;
    }

    /**
     * Gets the value of the deEnrollRsnCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeEnrollRsnCd() {
        return deEnrollRsnCd;
    }

    /**
     * Sets the value of the deEnrollRsnCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeEnrollRsnCd(String value) {
        this.deEnrollRsnCd = value;
    }

    /**
     * Gets the value of the badPayEndDt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBadPayEndDt() {
        return badPayEndDt;
    }

    /**
     * Sets the value of the badPayEndDt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBadPayEndDt(String value) {
        this.badPayEndDt = value;
    }

}
