//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.31 at 10:31:22 AM EDT 
//


package com.vzwcorp.pricinglab.vo.mcs.ezcheckout;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Details of APO ACH Payment Details
 * 
 * <p>Java class for ApoAchTransLogDetailsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ApoAchTransLogDetailsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.vzw.com/namespaces/scmplus}ApoAchPmtCreateDt" minOccurs="0"/>
 *         &lt;element ref="{http://www.vzw.com/namespaces/scmplus}ApoCcPmtCreateDt" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ApoAchTransLogDetailsType", propOrder = {
    "apoAchPmtCreateDt",
    "apoCcPmtCreateDt"
})
public class ApoAchTransLogDetailsType {

    @XmlElement(name = "ApoAchPmtCreateDt")
    protected String apoAchPmtCreateDt;
    @XmlElement(name = "ApoCcPmtCreateDt")
    protected String apoCcPmtCreateDt;

    /**
     * Gets the value of the apoAchPmtCreateDt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApoAchPmtCreateDt() {
        return apoAchPmtCreateDt;
    }

    /**
     * Sets the value of the apoAchPmtCreateDt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApoAchPmtCreateDt(String value) {
        this.apoAchPmtCreateDt = value;
    }

    /**
     * Gets the value of the apoCcPmtCreateDt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApoCcPmtCreateDt() {
        return apoCcPmtCreateDt;
    }

    /**
     * Sets the value of the apoCcPmtCreateDt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApoCcPmtCreateDt(String value) {
        this.apoCcPmtCreateDt = value;
    }

}
