//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.31 at 10:31:22 AM EDT 
//


package com.vzwcorp.pricinglab.vo.mcs.ezcheckout;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BlAcctPmtStatDetailsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BlAcctPmtStatDetailsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="blMethodCd" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="blPrtSuprsHld" type="{http://www.vzw.com/namespaces/scmplus}charType" minOccurs="0"/>
 *         &lt;element name="clientTransPath" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="deenrollRsnCd" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="effTmstamp" type="{http://www.vzw.com/namespaces/scmplus}DateTime" minOccurs="0"/>
 *         &lt;element name="enrollVenueCd" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="settleDay" type="{http://www.w3.org/2001/XMLSchema}short" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BlAcctPmtStatDetailsType", propOrder = {
    "blMethodCd",
    "blPrtSuprsHld",
    "clientTransPath",
    "deenrollRsnCd",
    "effTmstamp",
    "enrollVenueCd",
    "settleDay"
})
public class BlAcctPmtStatDetailsType {

    protected String blMethodCd;
    protected String blPrtSuprsHld;
    protected String clientTransPath;
    protected String deenrollRsnCd;
    protected String effTmstamp;
    protected String enrollVenueCd;
    protected Short settleDay;

    /**
     * Gets the value of the blMethodCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBlMethodCd() {
        return blMethodCd;
    }

    /**
     * Sets the value of the blMethodCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBlMethodCd(String value) {
        this.blMethodCd = value;
    }

    /**
     * Gets the value of the blPrtSuprsHld property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBlPrtSuprsHld() {
        return blPrtSuprsHld;
    }

    /**
     * Sets the value of the blPrtSuprsHld property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBlPrtSuprsHld(String value) {
        this.blPrtSuprsHld = value;
    }

    /**
     * Gets the value of the clientTransPath property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClientTransPath() {
        return clientTransPath;
    }

    /**
     * Sets the value of the clientTransPath property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClientTransPath(String value) {
        this.clientTransPath = value;
    }

    /**
     * Gets the value of the deenrollRsnCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeenrollRsnCd() {
        return deenrollRsnCd;
    }

    /**
     * Sets the value of the deenrollRsnCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeenrollRsnCd(String value) {
        this.deenrollRsnCd = value;
    }

    /**
     * Gets the value of the effTmstamp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEffTmstamp() {
        return effTmstamp;
    }

    /**
     * Sets the value of the effTmstamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEffTmstamp(String value) {
        this.effTmstamp = value;
    }

    /**
     * Gets the value of the enrollVenueCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEnrollVenueCd() {
        return enrollVenueCd;
    }

    /**
     * Sets the value of the enrollVenueCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEnrollVenueCd(String value) {
        this.enrollVenueCd = value;
    }

    /**
     * Gets the value of the settleDay property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getSettleDay() {
        return settleDay;
    }

    /**
     * Sets the value of the settleDay property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setSettleDay(Short value) {
        this.settleDay = value;
    }

}
