//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.31 at 10:31:22 AM EDT 
//


package com.vzwcorp.pricinglab.vo.mcs.ezcheckout;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Details of BlAcctCustMtn table
 * 
 * <p>Java class for BlAcctCustMtnType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BlAcctCustMtnType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Mdn" type="{http://www.vzw.com/namespaces/scmplus}NEW_MDNType" minOccurs="0"/>
 *         &lt;element name="BlTypCd" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CurPriInd" type="{http://www.vzw.com/namespaces/scmplus}charType" minOccurs="0"/>
 *         &lt;element name="CustMtnStatCd" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="MtnEffDt" type="{http://www.vzw.com/namespaces/scmplus}Date" minOccurs="0"/>
 *         &lt;element name="EffDt" type="{http://www.vzw.com/namespaces/scmplus}Date" minOccurs="0"/>
 *         &lt;element name="EndDt" type="{http://www.vzw.com/namespaces/scmplus}Date" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BlAcctCustMtnType", propOrder = {
    "mdn",
    "blTypCd",
    "curPriInd",
    "custMtnStatCd",
    "mtnEffDt",
    "effDt",
    "endDt"
})
public class BlAcctCustMtnType {

    @XmlElement(name = "Mdn")
    protected String mdn;
    @XmlElement(name = "BlTypCd")
    protected String blTypCd;
    @XmlElement(name = "CurPriInd")
    protected String curPriInd;
    @XmlElement(name = "CustMtnStatCd")
    protected String custMtnStatCd;
    @XmlElement(name = "MtnEffDt")
    protected String mtnEffDt;
    @XmlElement(name = "EffDt")
    protected String effDt;
    @XmlElement(name = "EndDt")
    protected String endDt;

    /**
     * Gets the value of the mdn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMdn() {
        return mdn;
    }

    /**
     * Sets the value of the mdn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMdn(String value) {
        this.mdn = value;
    }

    /**
     * Gets the value of the blTypCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBlTypCd() {
        return blTypCd;
    }

    /**
     * Sets the value of the blTypCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBlTypCd(String value) {
        this.blTypCd = value;
    }

    /**
     * Gets the value of the curPriInd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCurPriInd() {
        return curPriInd;
    }

    /**
     * Sets the value of the curPriInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCurPriInd(String value) {
        this.curPriInd = value;
    }

    /**
     * Gets the value of the custMtnStatCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustMtnStatCd() {
        return custMtnStatCd;
    }

    /**
     * Sets the value of the custMtnStatCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustMtnStatCd(String value) {
        this.custMtnStatCd = value;
    }

    /**
     * Gets the value of the mtnEffDt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMtnEffDt() {
        return mtnEffDt;
    }

    /**
     * Sets the value of the mtnEffDt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMtnEffDt(String value) {
        this.mtnEffDt = value;
    }

    /**
     * Gets the value of the effDt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEffDt() {
        return effDt;
    }

    /**
     * Sets the value of the effDt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEffDt(String value) {
        this.effDt = value;
    }

    /**
     * Gets the value of the endDt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEndDt() {
        return endDt;
    }

    /**
     * Sets the value of the endDt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEndDt(String value) {
        this.endDt = value;
    }

}
