//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.31 at 10:31:22 AM EDT 
//


package com.vzwcorp.pricinglab.vo.mcs.ezcheckout;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CustMtnSocMediaAddrDetailsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CustMtnSocMediaAddrDetailsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="socMediaTyp" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="socMediaAddr" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="addrTyp" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CustMtnSocMediaAddrDetailsType", propOrder = {
    "socMediaTyp",
    "socMediaAddr",
    "addrTyp"
})
public class CustMtnSocMediaAddrDetailsType {

    protected String socMediaTyp;
    protected String socMediaAddr;
    protected String addrTyp;

    /**
     * Gets the value of the socMediaTyp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSocMediaTyp() {
        return socMediaTyp;
    }

    /**
     * Sets the value of the socMediaTyp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSocMediaTyp(String value) {
        this.socMediaTyp = value;
    }

    /**
     * Gets the value of the socMediaAddr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSocMediaAddr() {
        return socMediaAddr;
    }

    /**
     * Sets the value of the socMediaAddr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSocMediaAddr(String value) {
        this.socMediaAddr = value;
    }

    /**
     * Gets the value of the addrTyp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddrTyp() {
        return addrTyp;
    }

    /**
     * Sets the value of the addrTyp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddrTyp(String value) {
        this.addrTyp = value;
    }

}
