//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.31 at 10:31:22 AM EDT 
//


package com.vzwcorp.pricinglab.vo.mcs.ezcheckout;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.vzw.com/namespaces/scmplus}DiscountPrice" minOccurs="0"/>
 *         &lt;element ref="{http://www.vzw.com/namespaces/scmplus}DiscountInfo" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "discountPrice",
    "discountInfo"
})
@XmlRootElement(name = "DiscountDetails")
public class DiscountDetails {

    @XmlElement(name = "DiscountPrice", nillable = true)
    protected Double discountPrice;
    @XmlElement(name = "DiscountInfo")
    protected DiscountInfo discountInfo;

    /**
     * Gets the value of the discountPrice property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getDiscountPrice() {
        return discountPrice;
    }

    /**
     * Sets the value of the discountPrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setDiscountPrice(Double value) {
        this.discountPrice = value;
    }

    /**
     * Gets the value of the discountInfo property.
     * 
     * @return
     *     possible object is
     *     {@link DiscountInfo }
     *     
     */
    public DiscountInfo getDiscountInfo() {
        return discountInfo;
    }

    /**
     * Sets the value of the discountInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link DiscountInfo }
     *     
     */
    public void setDiscountInfo(DiscountInfo value) {
        this.discountInfo = value;
    }

}
