//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.31 at 10:31:22 AM EDT 
//


package com.vzwcorp.pricinglab.vo.mcs.ezcheckout;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EnterpriseCustomerDetailsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EnterpriseCustomerDetailsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="billday" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="bsnsConsumerCd" type="{http://www.vzw.com/namespaces/scmplus}charType" minOccurs="0"/>
 *         &lt;element name="bsnsNme" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="cbrEffTs" type="{http://www.vzw.com/namespaces/scmplus}DateTime" minOccurs="0"/>
 *         &lt;element name="custArchStatCd" type="{http://www.vzw.com/namespaces/scmplus}charType" minOccurs="0"/>
 *         &lt;element name="custAssocIdNo" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="custClassCd" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="custPassword" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="custStatCd" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="custTypCd" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="customerID" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="customerType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ecpdEffDt" type="{http://www.vzw.com/namespaces/scmplus}Date" minOccurs="0"/>
 *         &lt;element name="ecpdProfileId" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="familyName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="fedTaxIdNo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="givenName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="liabilityTypeCd" type="{http://www.vzw.com/namespaces/scmplus}charType" minOccurs="0"/>
 *         &lt;element name="middleInit" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="personIdNo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="slsRepId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ssn" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="statReasonCd" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="suffixName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EnterpriseCustomerDetailsType", propOrder = {
    "billday",
    "bsnsConsumerCd",
    "bsnsNme",
    "cbrEffTs",
    "custArchStatCd",
    "custAssocIdNo",
    "custClassCd",
    "custPassword",
    "custStatCd",
    "custTypCd",
    "customerID",
    "customerType",
    "ecpdEffDt",
    "ecpdProfileId",
    "familyName",
    "fedTaxIdNo",
    "givenName",
    "liabilityTypeCd",
    "middleInit",
    "personIdNo",
    "slsRepId",
    "ssn",
    "statReasonCd",
    "suffixName"
})
public class EnterpriseCustomerDetailsType {

    protected String billday;
    protected String bsnsConsumerCd;
    protected String bsnsNme;
    protected String cbrEffTs;
    protected String custArchStatCd;
    protected BigInteger custAssocIdNo;
    protected String custClassCd;
    protected String custPassword;
    protected String custStatCd;
    protected String custTypCd;
    protected BigInteger customerID;
    protected String customerType;
    protected String ecpdEffDt;
    protected BigInteger ecpdProfileId;
    protected String familyName;
    protected String fedTaxIdNo;
    protected String givenName;
    protected String liabilityTypeCd;
    protected String middleInit;
    protected String personIdNo;
    protected String slsRepId;
    protected String ssn;
    protected String statReasonCd;
    protected String suffixName;

    /**
     * Gets the value of the billday property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBillday() {
        return billday;
    }

    /**
     * Sets the value of the billday property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBillday(String value) {
        this.billday = value;
    }

    /**
     * Gets the value of the bsnsConsumerCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBsnsConsumerCd() {
        return bsnsConsumerCd;
    }

    /**
     * Sets the value of the bsnsConsumerCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBsnsConsumerCd(String value) {
        this.bsnsConsumerCd = value;
    }

    /**
     * Gets the value of the bsnsNme property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBsnsNme() {
        return bsnsNme;
    }

    /**
     * Sets the value of the bsnsNme property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBsnsNme(String value) {
        this.bsnsNme = value;
    }

    /**
     * Gets the value of the cbrEffTs property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCbrEffTs() {
        return cbrEffTs;
    }

    /**
     * Sets the value of the cbrEffTs property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCbrEffTs(String value) {
        this.cbrEffTs = value;
    }

    /**
     * Gets the value of the custArchStatCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustArchStatCd() {
        return custArchStatCd;
    }

    /**
     * Sets the value of the custArchStatCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustArchStatCd(String value) {
        this.custArchStatCd = value;
    }

    /**
     * Gets the value of the custAssocIdNo property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCustAssocIdNo() {
        return custAssocIdNo;
    }

    /**
     * Sets the value of the custAssocIdNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCustAssocIdNo(BigInteger value) {
        this.custAssocIdNo = value;
    }

    /**
     * Gets the value of the custClassCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustClassCd() {
        return custClassCd;
    }

    /**
     * Sets the value of the custClassCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustClassCd(String value) {
        this.custClassCd = value;
    }

    /**
     * Gets the value of the custPassword property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustPassword() {
        return custPassword;
    }

    /**
     * Sets the value of the custPassword property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustPassword(String value) {
        this.custPassword = value;
    }

    /**
     * Gets the value of the custStatCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustStatCd() {
        return custStatCd;
    }

    /**
     * Sets the value of the custStatCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustStatCd(String value) {
        this.custStatCd = value;
    }

    /**
     * Gets the value of the custTypCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustTypCd() {
        return custTypCd;
    }

    /**
     * Sets the value of the custTypCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustTypCd(String value) {
        this.custTypCd = value;
    }

    /**
     * Gets the value of the customerID property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCustomerID() {
        return customerID;
    }

    /**
     * Sets the value of the customerID property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCustomerID(BigInteger value) {
        this.customerID = value;
    }

    /**
     * Gets the value of the customerType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerType() {
        return customerType;
    }

    /**
     * Sets the value of the customerType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerType(String value) {
        this.customerType = value;
    }

    /**
     * Gets the value of the ecpdEffDt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEcpdEffDt() {
        return ecpdEffDt;
    }

    /**
     * Sets the value of the ecpdEffDt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEcpdEffDt(String value) {
        this.ecpdEffDt = value;
    }

    /**
     * Gets the value of the ecpdProfileId property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getEcpdProfileId() {
        return ecpdProfileId;
    }

    /**
     * Sets the value of the ecpdProfileId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setEcpdProfileId(BigInteger value) {
        this.ecpdProfileId = value;
    }

    /**
     * Gets the value of the familyName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFamilyName() {
        return familyName;
    }

    /**
     * Sets the value of the familyName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFamilyName(String value) {
        this.familyName = value;
    }

    /**
     * Gets the value of the fedTaxIdNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFedTaxIdNo() {
        return fedTaxIdNo;
    }

    /**
     * Sets the value of the fedTaxIdNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFedTaxIdNo(String value) {
        this.fedTaxIdNo = value;
    }

    /**
     * Gets the value of the givenName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGivenName() {
        return givenName;
    }

    /**
     * Sets the value of the givenName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGivenName(String value) {
        this.givenName = value;
    }

    /**
     * Gets the value of the liabilityTypeCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLiabilityTypeCd() {
        return liabilityTypeCd;
    }

    /**
     * Sets the value of the liabilityTypeCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLiabilityTypeCd(String value) {
        this.liabilityTypeCd = value;
    }

    /**
     * Gets the value of the middleInit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMiddleInit() {
        return middleInit;
    }

    /**
     * Sets the value of the middleInit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMiddleInit(String value) {
        this.middleInit = value;
    }

    /**
     * Gets the value of the personIdNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPersonIdNo() {
        return personIdNo;
    }

    /**
     * Sets the value of the personIdNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPersonIdNo(String value) {
        this.personIdNo = value;
    }

    /**
     * Gets the value of the slsRepId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSlsRepId() {
        return slsRepId;
    }

    /**
     * Sets the value of the slsRepId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSlsRepId(String value) {
        this.slsRepId = value;
    }

    /**
     * Gets the value of the ssn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSsn() {
        return ssn;
    }

    /**
     * Sets the value of the ssn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSsn(String value) {
        this.ssn = value;
    }

    /**
     * Gets the value of the statReasonCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatReasonCd() {
        return statReasonCd;
    }

    /**
     * Sets the value of the statReasonCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatReasonCd(String value) {
        this.statReasonCd = value;
    }

    /**
     * Gets the value of the suffixName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSuffixName() {
        return suffixName;
    }

    /**
     * Sets the value of the suffixName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSuffixName(String value) {
        this.suffixName = value;
    }

}
