//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.31 at 10:31:22 AM EDT 
//


package com.vzwcorp.pricinglab.vo.mcs.ezcheckout;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EqOrdInstallLoanDetailsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EqOrdInstallLoanDetailsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="eoLoanStatCd" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="eqOrdNo" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="installLoanAmt" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="installLoanNo" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="mdn" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="netaceLocId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EqOrdInstallLoanDetailsType", propOrder = {
    "eoLoanStatCd",
    "eqOrdNo",
    "installLoanAmt",
    "installLoanNo",
    "mdn",
    "netaceLocId"
})
public class EqOrdInstallLoanDetailsType {

    protected String eoLoanStatCd;
    protected BigInteger eqOrdNo;
    protected String installLoanAmt;
    protected BigInteger installLoanNo;
    protected String mdn;
    protected String netaceLocId;

    /**
     * Gets the value of the eoLoanStatCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEoLoanStatCd() {
        return eoLoanStatCd;
    }

    /**
     * Sets the value of the eoLoanStatCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEoLoanStatCd(String value) {
        this.eoLoanStatCd = value;
    }

    /**
     * Gets the value of the eqOrdNo property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getEqOrdNo() {
        return eqOrdNo;
    }

    /**
     * Sets the value of the eqOrdNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setEqOrdNo(BigInteger value) {
        this.eqOrdNo = value;
    }

    /**
     * Gets the value of the installLoanAmt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInstallLoanAmt() {
        return installLoanAmt;
    }

    /**
     * Sets the value of the installLoanAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInstallLoanAmt(String value) {
        this.installLoanAmt = value;
    }

    /**
     * Gets the value of the installLoanNo property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getInstallLoanNo() {
        return installLoanNo;
    }

    /**
     * Sets the value of the installLoanNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setInstallLoanNo(BigInteger value) {
        this.installLoanNo = value;
    }

    /**
     * Gets the value of the mdn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMdn() {
        return mdn;
    }

    /**
     * Sets the value of the mdn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMdn(String value) {
        this.mdn = value;
    }

    /**
     * Gets the value of the netaceLocId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNetaceLocId() {
        return netaceLocId;
    }

    /**
     * Sets the value of the netaceLocId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNetaceLocId(String value) {
        this.netaceLocId = value;
    }

}
