//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.31 at 10:31:22 AM EDT 
//


package com.vzwcorp.pricinglab.vo.mcs.ezcheckout;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.vzw.com/namespaces/scmplus}JukeboxID" minOccurs="0"/>
 *         &lt;element ref="{http://www.vzw.com/namespaces/scmplus}Name"/>
 *         &lt;element ref="{http://www.vzw.com/namespaces/scmplus}CollectionName" minOccurs="0"/>
 *         &lt;element ref="{http://www.vzw.com/namespaces/scmplus}RBTContent" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="EnterpriseCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element ref="{http://www.vzw.com/namespaces/scmplus}IsEnterprise" minOccurs="0"/>
 *         &lt;element name="IsDefault" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="Y"/>
 *               &lt;enumeration value="N"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "jukeboxID",
    "name",
    "collectionName",
    "rbtContent",
    "enterpriseCode",
    "isEnterprise",
    "isDefault"
})
@XmlRootElement(name = "JukeboxContent")
public class JukeboxContent {

    @XmlElement(name = "JukeboxID")
    protected String jukeboxID;
    @XmlElement(name = "Name", required = true)
    protected String name;
    @XmlElement(name = "CollectionName")
    protected String collectionName;
    @XmlElement(name = "RBTContent")
    protected List<RBTContent> rbtContent;
    @XmlElement(name = "EnterpriseCode")
    protected String enterpriseCode;
    @XmlElement(name = "IsEnterprise")
    protected String isEnterprise;
    @XmlElement(name = "IsDefault")
    protected String isDefault;

    /**
     * Gets the value of the jukeboxID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJukeboxID() {
        return jukeboxID;
    }

    /**
     * Sets the value of the jukeboxID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJukeboxID(String value) {
        this.jukeboxID = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the collectionName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCollectionName() {
        return collectionName;
    }

    /**
     * Sets the value of the collectionName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCollectionName(String value) {
        this.collectionName = value;
    }

    /**
     * Gets the value of the rbtContent property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the rbtContent property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRBTContent().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RBTContent }
     * 
     * 
     */
    public List<RBTContent> getRBTContent() {
        if (rbtContent == null) {
            rbtContent = new ArrayList<RBTContent>();
        }
        return this.rbtContent;
    }

    /**
     * Gets the value of the enterpriseCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEnterpriseCode() {
        return enterpriseCode;
    }

    /**
     * Sets the value of the enterpriseCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEnterpriseCode(String value) {
        this.enterpriseCode = value;
    }

    /**
     * Gets the value of the isEnterprise property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsEnterprise() {
        return isEnterprise;
    }

    /**
     * Sets the value of the isEnterprise property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsEnterprise(String value) {
        this.isEnterprise = value;
    }

    /**
     * Gets the value of the isDefault property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsDefault() {
        return isDefault;
    }

    /**
     * Sets the value of the isDefault property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsDefault(String value) {
        this.isDefault = value;
    }

}
