//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.31 at 10:31:22 AM EDT 
//


package com.vzwcorp.pricinglab.vo.mcs.ezcheckout;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for LnPrimIdNonGeoMdnDetailsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LnPrimIdNonGeoMdnDetailsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="lnNonGeoMdnEffTs" type="{http://www.vzw.com/namespaces/scmplus}DateTime" minOccurs="0"/>
 *         &lt;element name="nonGeoMdn" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LnPrimIdNonGeoMdnDetailsType", propOrder = {
    "lnNonGeoMdnEffTs",
    "nonGeoMdn"
})
public class LnPrimIdNonGeoMdnDetailsType {

    protected String lnNonGeoMdnEffTs;
    protected String nonGeoMdn;

    /**
     * Gets the value of the lnNonGeoMdnEffTs property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLnNonGeoMdnEffTs() {
        return lnNonGeoMdnEffTs;
    }

    /**
     * Sets the value of the lnNonGeoMdnEffTs property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLnNonGeoMdnEffTs(String value) {
        this.lnNonGeoMdnEffTs = value;
    }

    /**
     * Gets the value of the nonGeoMdn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNonGeoMdn() {
        return nonGeoMdn;
    }

    /**
     * Sets the value of the nonGeoMdn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNonGeoMdn(String value) {
        this.nonGeoMdn = value;
    }

}
