//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.31 at 10:31:22 AM EDT 
//


package com.vzwcorp.pricinglab.vo.mcs.ezcheckout;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for LnPrimIdDvcOnlyDetailsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LnPrimIdDvcOnlyDetailsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="deviceId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="deviceIdTyp" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="lnDvcIdEffTs" type="{http://www.vzw.com/namespaces/scmplus}DateTime" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LnPrimIdDvcOnlyDetailsType", propOrder = {
    "deviceId",
    "deviceIdTyp",
    "lnDvcIdEffTs"
})
public class LnPrimIdDvcOnlyDetailsType {

    protected String deviceId;
    protected String deviceIdTyp;
    protected String lnDvcIdEffTs;

    /**
     * Gets the value of the deviceId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeviceId() {
        return deviceId;
    }

    /**
     * Sets the value of the deviceId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeviceId(String value) {
        this.deviceId = value;
    }

    /**
     * Gets the value of the deviceIdTyp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeviceIdTyp() {
        return deviceIdTyp;
    }

    /**
     * Sets the value of the deviceIdTyp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeviceIdTyp(String value) {
        this.deviceIdTyp = value;
    }

    /**
     * Gets the value of the lnDvcIdEffTs property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLnDvcIdEffTs() {
        return lnDvcIdEffTs;
    }

    /**
     * Sets the value of the lnDvcIdEffTs property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLnDvcIdEffTs(String value) {
        this.lnDvcIdEffTs = value;
    }

}
