//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.31 at 10:31:22 AM EDT 
//


package com.vzwcorp.pricinglab.vo.mcs.ezcheckout;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Details of Customer Device Details 
 * 
 * <p>Java class for LnValidCustDvcDetailsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LnValidCustDvcDetailsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.vzw.com/namespaces/scmplus}CustDvcEqpTrnDetails" minOccurs="0"/>
 *         &lt;element ref="{http://www.vzw.com/namespaces/scmplus}CustDvcEqpEligDetails" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LnValidCustDvcDetailsType", propOrder = {
    "custDvcEqpTrnDetails",
    "custDvcEqpEligDetails"
})
public class LnValidCustDvcDetailsType {

    @XmlElement(name = "CustDvcEqpTrnDetails")
    protected CustDvcEqpTrnDetails custDvcEqpTrnDetails;
    @XmlElement(name = "CustDvcEqpEligDetails")
    protected CustDvcEqpEligDetails custDvcEqpEligDetails;

    /**
     * Gets the value of the custDvcEqpTrnDetails property.
     * 
     * @return
     *     possible object is
     *     {@link CustDvcEqpTrnDetails }
     *     
     */
    public CustDvcEqpTrnDetails getCustDvcEqpTrnDetails() {
        return custDvcEqpTrnDetails;
    }

    /**
     * Sets the value of the custDvcEqpTrnDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link CustDvcEqpTrnDetails }
     *     
     */
    public void setCustDvcEqpTrnDetails(CustDvcEqpTrnDetails value) {
        this.custDvcEqpTrnDetails = value;
    }

    /**
     * Gets the value of the custDvcEqpEligDetails property.
     * 
     * @return
     *     possible object is
     *     {@link CustDvcEqpEligDetails }
     *     
     */
    public CustDvcEqpEligDetails getCustDvcEqpEligDetails() {
        return custDvcEqpEligDetails;
    }

    /**
     * Sets the value of the custDvcEqpEligDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link CustDvcEqpEligDetails }
     *     
     */
    public void setCustDvcEqpEligDetails(CustDvcEqpEligDetails value) {
        this.custDvcEqpEligDetails = value;
    }

}
