//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.31 at 10:31:22 AM EDT 
//


package com.vzwcorp.pricinglab.vo.mcs.ezcheckout;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Details of Customer
 * 
 * <p>Java class for MabDetailsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MabDetailsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.vzw.com/namespaces/scmplus}MabDestCd" minOccurs="0"/>
 *         &lt;element ref="{http://www.vzw.com/namespaces/scmplus}MabMajAcctType" minOccurs="0"/>
 *         &lt;element ref="{http://www.vzw.com/namespaces/scmplus}MabMajAcctNo" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MabDetailsType", propOrder = {
    "mabDestCd",
    "mabMajAcctType",
    "mabMajAcctNo"
})
public class MabDetailsType {

    @XmlElement(name = "MabDestCd")
    protected String mabDestCd;
    @XmlElement(name = "MabMajAcctType")
    protected BigInteger mabMajAcctType;
    @XmlElement(name = "MabMajAcctNo")
    protected String mabMajAcctNo;

    /**
     * Gets the value of the mabDestCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMabDestCd() {
        return mabDestCd;
    }

    /**
     * Sets the value of the mabDestCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMabDestCd(String value) {
        this.mabDestCd = value;
    }

    /**
     * Gets the value of the mabMajAcctType property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getMabMajAcctType() {
        return mabMajAcctType;
    }

    /**
     * Sets the value of the mabMajAcctType property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setMabMajAcctType(BigInteger value) {
        this.mabMajAcctType = value;
    }

    /**
     * Gets the value of the mabMajAcctNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMabMajAcctNo() {
        return mabMajAcctNo;
    }

    /**
     * Sets the value of the mabMajAcctNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMabMajAcctNo(String value) {
        this.mabMajAcctNo = value;
    }

}
