//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.31 at 10:31:22 AM EDT 
//


package com.vzwcorp.pricinglab.vo.mcs.ezcheckout;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MdnStatusUpdateDetailsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MdnStatusUpdateDetailsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="autoPortCd" type="{http://www.vzw.com/namespaces/scmplus}charType" minOccurs="0"/>
 *         &lt;element name="blTypCd" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="currPriInd" type="{http://www.vzw.com/namespaces/scmplus}charType" minOccurs="0"/>
 *         &lt;element name="custMtnStatCd" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="dirFillPortCd" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="effDt" type="{http://www.vzw.com/namespaces/scmplus}Date" minOccurs="0"/>
 *         &lt;element name="effTmstamp" type="{http://www.vzw.com/namespaces/scmplus}DateTime" minOccurs="0"/>
 *         &lt;element name="endDt" type="{http://www.vzw.com/namespaces/scmplus}Date" minOccurs="0"/>
 *         &lt;element name="endTmstamp" type="{http://www.vzw.com/namespaces/scmplus}DateTime" minOccurs="0"/>
 *         &lt;element name="mdn" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="mtnEffDt" type="{http://www.vzw.com/namespaces/scmplus}Date" minOccurs="0"/>
 *         &lt;element name="portInConfirmCd" type="{http://www.vzw.com/namespaces/scmplus}charType" minOccurs="0"/>
 *         &lt;element name="statReasonCd" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MdnStatusUpdateDetailsType", propOrder = {
    "autoPortCd",
    "blTypCd",
    "currPriInd",
    "custMtnStatCd",
    "dirFillPortCd",
    "effDt",
    "effTmstamp",
    "endDt",
    "endTmstamp",
    "mdn",
    "mtnEffDt",
    "portInConfirmCd",
    "statReasonCd"
})
public class MdnStatusUpdateDetailsType {

    protected String autoPortCd;
    protected String blTypCd;
    protected String currPriInd;
    protected String custMtnStatCd;
    protected String dirFillPortCd;
    protected String effDt;
    protected String effTmstamp;
    protected String endDt;
    protected String endTmstamp;
    protected String mdn;
    protected String mtnEffDt;
    protected String portInConfirmCd;
    protected String statReasonCd;

    /**
     * Gets the value of the autoPortCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAutoPortCd() {
        return autoPortCd;
    }

    /**
     * Sets the value of the autoPortCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAutoPortCd(String value) {
        this.autoPortCd = value;
    }

    /**
     * Gets the value of the blTypCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBlTypCd() {
        return blTypCd;
    }

    /**
     * Sets the value of the blTypCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBlTypCd(String value) {
        this.blTypCd = value;
    }

    /**
     * Gets the value of the currPriInd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCurrPriInd() {
        return currPriInd;
    }

    /**
     * Sets the value of the currPriInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCurrPriInd(String value) {
        this.currPriInd = value;
    }

    /**
     * Gets the value of the custMtnStatCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustMtnStatCd() {
        return custMtnStatCd;
    }

    /**
     * Sets the value of the custMtnStatCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustMtnStatCd(String value) {
        this.custMtnStatCd = value;
    }

    /**
     * Gets the value of the dirFillPortCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDirFillPortCd() {
        return dirFillPortCd;
    }

    /**
     * Sets the value of the dirFillPortCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDirFillPortCd(String value) {
        this.dirFillPortCd = value;
    }

    /**
     * Gets the value of the effDt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEffDt() {
        return effDt;
    }

    /**
     * Sets the value of the effDt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEffDt(String value) {
        this.effDt = value;
    }

    /**
     * Gets the value of the effTmstamp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEffTmstamp() {
        return effTmstamp;
    }

    /**
     * Sets the value of the effTmstamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEffTmstamp(String value) {
        this.effTmstamp = value;
    }

    /**
     * Gets the value of the endDt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEndDt() {
        return endDt;
    }

    /**
     * Sets the value of the endDt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEndDt(String value) {
        this.endDt = value;
    }

    /**
     * Gets the value of the endTmstamp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEndTmstamp() {
        return endTmstamp;
    }

    /**
     * Sets the value of the endTmstamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEndTmstamp(String value) {
        this.endTmstamp = value;
    }

    /**
     * Gets the value of the mdn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMdn() {
        return mdn;
    }

    /**
     * Sets the value of the mdn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMdn(String value) {
        this.mdn = value;
    }

    /**
     * Gets the value of the mtnEffDt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMtnEffDt() {
        return mtnEffDt;
    }

    /**
     * Sets the value of the mtnEffDt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMtnEffDt(String value) {
        this.mtnEffDt = value;
    }

    /**
     * Gets the value of the portInConfirmCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPortInConfirmCd() {
        return portInConfirmCd;
    }

    /**
     * Sets the value of the portInConfirmCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPortInConfirmCd(String value) {
        this.portInConfirmCd = value;
    }

    /**
     * Gets the value of the statReasonCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatReasonCd() {
        return statReasonCd;
    }

    /**
     * Sets the value of the statReasonCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatReasonCd(String value) {
        this.statReasonCd = value;
    }

}
