//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.31 at 10:31:22 AM EDT 
//


package com.vzwcorp.pricinglab.vo.mcs.ezcheckout;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for OrdLnDetailsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OrdLnDetailsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="mtn" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ordLnItmDetails" type="{http://www.vzw.com/namespaces/scmplus}OrdLnItemDetailsType" minOccurs="0"/>
 *         &lt;element name="ordLnSimDetails" type="{http://www.vzw.com/namespaces/scmplus}OrdLnSimDetailsType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OrdLnDetailsType", propOrder = {
    "mtn",
    "ordLnItmDetails",
    "ordLnSimDetails"
})
public class OrdLnDetailsType {

    protected String mtn;
    protected OrdLnItemDetailsType ordLnItmDetails;
    protected OrdLnSimDetailsType ordLnSimDetails;

    /**
     * Gets the value of the mtn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMtn() {
        return mtn;
    }

    /**
     * Sets the value of the mtn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMtn(String value) {
        this.mtn = value;
    }

    /**
     * Gets the value of the ordLnItmDetails property.
     * 
     * @return
     *     possible object is
     *     {@link OrdLnItemDetailsType }
     *     
     */
    public OrdLnItemDetailsType getOrdLnItmDetails() {
        return ordLnItmDetails;
    }

    /**
     * Sets the value of the ordLnItmDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrdLnItemDetailsType }
     *     
     */
    public void setOrdLnItmDetails(OrdLnItemDetailsType value) {
        this.ordLnItmDetails = value;
    }

    /**
     * Gets the value of the ordLnSimDetails property.
     * 
     * @return
     *     possible object is
     *     {@link OrdLnSimDetailsType }
     *     
     */
    public OrdLnSimDetailsType getOrdLnSimDetails() {
        return ordLnSimDetails;
    }

    /**
     * Sets the value of the ordLnSimDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrdLnSimDetailsType }
     *     
     */
    public void setOrdLnSimDetails(OrdLnSimDetailsType value) {
        this.ordLnSimDetails = value;
    }

}
