//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.31 at 10:31:22 AM EDT 
//


package com.vzwcorp.pricinglab.vo.mcs.ezcheckout;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for OrdLnSvcConsentListType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OrdLnSvcConsentListType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="OrdLnSvcConsent" type="{http://www.vzw.com/namespaces/scmplus}OrdLnSvcConsentType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OrdLnSvcConsentListType", propOrder = {
    "ordLnSvcConsent"
})
public class OrdLnSvcConsentListType {

    @XmlElement(name = "OrdLnSvcConsent")
    protected List<OrdLnSvcConsentType> ordLnSvcConsent;

    /**
     * Gets the value of the ordLnSvcConsent property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ordLnSvcConsent property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOrdLnSvcConsent().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OrdLnSvcConsentType }
     * 
     * 
     */
    public List<OrdLnSvcConsentType> getOrdLnSvcConsent() {
        if (ordLnSvcConsent == null) {
            ordLnSvcConsent = new ArrayList<OrdLnSvcConsentType>();
        }
        return this.ordLnSvcConsent;
    }

}
