//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.31 at 10:31:22 AM EDT 
//


package com.vzwcorp.pricinglab.vo.mcs.ezcheckout;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PrlLookupDetailsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PrlLookupDetailsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="billSysID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="bsAccountNum" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="bsCustomerId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="lnFullfillReqDt" type="{http://www.vzw.com/namespaces/scmplus}Date" minOccurs="0"/>
 *         &lt;element name="lnItmCreateDt" type="{http://www.vzw.com/namespaces/scmplus}Date" minOccurs="0"/>
 *         &lt;element name="lnItmNo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="lnItmTypCd" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="mdn" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="offrTypCD" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="offrTypID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="orderNo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="prlRequestID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="prlRequestIdTyp" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PrlLookupDetailsType", propOrder = {
    "billSysID",
    "bsAccountNum",
    "bsCustomerId",
    "lnFullfillReqDt",
    "lnItmCreateDt",
    "lnItmNo",
    "lnItmTypCd",
    "mdn",
    "offrTypCD",
    "offrTypID",
    "orderNo",
    "prlRequestID",
    "prlRequestIdTyp"
})
public class PrlLookupDetailsType {

    protected String billSysID;
    protected String bsAccountNum;
    protected String bsCustomerId;
    protected String lnFullfillReqDt;
    protected String lnItmCreateDt;
    protected String lnItmNo;
    protected String lnItmTypCd;
    protected String mdn;
    protected String offrTypCD;
    protected String offrTypID;
    protected String orderNo;
    protected String prlRequestID;
    protected String prlRequestIdTyp;

    /**
     * Gets the value of the billSysID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBillSysID() {
        return billSysID;
    }

    /**
     * Sets the value of the billSysID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBillSysID(String value) {
        this.billSysID = value;
    }

    /**
     * Gets the value of the bsAccountNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBsAccountNum() {
        return bsAccountNum;
    }

    /**
     * Sets the value of the bsAccountNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBsAccountNum(String value) {
        this.bsAccountNum = value;
    }

    /**
     * Gets the value of the bsCustomerId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBsCustomerId() {
        return bsCustomerId;
    }

    /**
     * Sets the value of the bsCustomerId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBsCustomerId(String value) {
        this.bsCustomerId = value;
    }

    /**
     * Gets the value of the lnFullfillReqDt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLnFullfillReqDt() {
        return lnFullfillReqDt;
    }

    /**
     * Sets the value of the lnFullfillReqDt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLnFullfillReqDt(String value) {
        this.lnFullfillReqDt = value;
    }

    /**
     * Gets the value of the lnItmCreateDt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLnItmCreateDt() {
        return lnItmCreateDt;
    }

    /**
     * Sets the value of the lnItmCreateDt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLnItmCreateDt(String value) {
        this.lnItmCreateDt = value;
    }

    /**
     * Gets the value of the lnItmNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLnItmNo() {
        return lnItmNo;
    }

    /**
     * Sets the value of the lnItmNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLnItmNo(String value) {
        this.lnItmNo = value;
    }

    /**
     * Gets the value of the lnItmTypCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLnItmTypCd() {
        return lnItmTypCd;
    }

    /**
     * Sets the value of the lnItmTypCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLnItmTypCd(String value) {
        this.lnItmTypCd = value;
    }

    /**
     * Gets the value of the mdn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMdn() {
        return mdn;
    }

    /**
     * Sets the value of the mdn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMdn(String value) {
        this.mdn = value;
    }

    /**
     * Gets the value of the offrTypCD property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOffrTypCD() {
        return offrTypCD;
    }

    /**
     * Sets the value of the offrTypCD property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOffrTypCD(String value) {
        this.offrTypCD = value;
    }

    /**
     * Gets the value of the offrTypID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOffrTypID() {
        return offrTypID;
    }

    /**
     * Sets the value of the offrTypID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOffrTypID(String value) {
        this.offrTypID = value;
    }

    /**
     * Gets the value of the orderNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrderNo() {
        return orderNo;
    }

    /**
     * Sets the value of the orderNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrderNo(String value) {
        this.orderNo = value;
    }

    /**
     * Gets the value of the prlRequestID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrlRequestID() {
        return prlRequestID;
    }

    /**
     * Sets the value of the prlRequestID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrlRequestID(String value) {
        this.prlRequestID = value;
    }

    /**
     * Gets the value of the prlRequestIdTyp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrlRequestIdTyp() {
        return prlRequestIdTyp;
    }

    /**
     * Sets the value of the prlRequestIdTyp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrlRequestIdTyp(String value) {
        this.prlRequestIdTyp = value;
    }

}
