//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.31 at 10:31:22 AM EDT 
//


package com.vzwcorp.pricinglab.vo.mcs.ezcheckout;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.vzw.com/namespaces/scmplus}ItemID" minOccurs="0"/>
 *         &lt;element ref="{http://www.vzw.com/namespaces/scmplus}ContentID"/>
 *         &lt;element ref="{http://www.vzw.com/namespaces/scmplus}IsJukebox" minOccurs="0"/>
 *         &lt;element name="Title" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element ref="{http://www.vzw.com/namespaces/scmplus}ArtistName" minOccurs="0"/>
 *         &lt;element name="DateAdded" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="ExpiryDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element ref="{http://www.vzw.com/namespaces/scmplus}Preview" minOccurs="0"/>
 *         &lt;element ref="{http://www.vzw.com/namespaces/scmplus}Icon" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.vzw.com/namespaces/scmplus}DeviceIcon" minOccurs="0"/>
 *         &lt;element name="IsDefault" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="Y"/>
 *               &lt;enumeration value="N"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element ref="{http://www.vzw.com/namespaces/scmplus}CollectionName" minOccurs="0"/>
 *         &lt;element name="PricePlanPackage" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;extension base="{http://www.vzw.com/namespaces/scmplus}PricePlanPackage-Type">
 *               &lt;/extension>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element ref="{http://www.vzw.com/namespaces/scmplus}ReleaseYear" minOccurs="0"/>
 *         &lt;element ref="{http://www.vzw.com/namespaces/scmplus}IsEnterprise" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "itemID",
    "contentID",
    "isJukebox",
    "title",
    "artistName",
    "dateAdded",
    "expiryDate",
    "preview",
    "icon",
    "deviceIcon",
    "isDefault",
    "collectionName",
    "pricePlanPackage",
    "releaseYear",
    "isEnterprise"
})
@XmlRootElement(name = "RBTContent")
public class RBTContent {

    @XmlElement(name = "ItemID")
    protected String itemID;
    @XmlElement(name = "ContentID", required = true)
    protected String contentID;
    @XmlElement(name = "IsJukebox")
    protected String isJukebox;
    @XmlElement(name = "Title")
    protected String title;
    @XmlElement(name = "ArtistName")
    protected String artistName;
    @XmlElement(name = "DateAdded")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar dateAdded;
    @XmlElement(name = "ExpiryDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar expiryDate;
    @XmlElement(name = "Preview")
    protected FileType preview;
    @XmlElement(name = "Icon")
    protected List<FileType> icon;
    @XmlElement(name = "DeviceIcon")
    protected FileType deviceIcon;
    @XmlElement(name = "IsDefault")
    protected String isDefault;
    @XmlElement(name = "CollectionName")
    protected String collectionName;
    @XmlElement(name = "PricePlanPackage")
    protected List<RBTContent.PricePlanPackage> pricePlanPackage;
    @XmlElement(name = "ReleaseYear")
    protected Long releaseYear;
    @XmlElement(name = "IsEnterprise")
    protected String isEnterprise;

    /**
     * Gets the value of the itemID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getItemID() {
        return itemID;
    }

    /**
     * Sets the value of the itemID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setItemID(String value) {
        this.itemID = value;
    }

    /**
     * Gets the value of the contentID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContentID() {
        return contentID;
    }

    /**
     * Sets the value of the contentID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContentID(String value) {
        this.contentID = value;
    }

    /**
     * Gets the value of the isJukebox property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsJukebox() {
        return isJukebox;
    }

    /**
     * Sets the value of the isJukebox property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsJukebox(String value) {
        this.isJukebox = value;
    }

    /**
     * Gets the value of the title property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitle(String value) {
        this.title = value;
    }

    /**
     * Gets the value of the artistName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getArtistName() {
        return artistName;
    }

    /**
     * Sets the value of the artistName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setArtistName(String value) {
        this.artistName = value;
    }

    /**
     * Gets the value of the dateAdded property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDateAdded() {
        return dateAdded;
    }

    /**
     * Sets the value of the dateAdded property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDateAdded(XMLGregorianCalendar value) {
        this.dateAdded = value;
    }

    /**
     * Gets the value of the expiryDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getExpiryDate() {
        return expiryDate;
    }

    /**
     * Sets the value of the expiryDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setExpiryDate(XMLGregorianCalendar value) {
        this.expiryDate = value;
    }

    /**
     * Gets the value of the preview property.
     * 
     * @return
     *     possible object is
     *     {@link FileType }
     *     
     */
    public FileType getPreview() {
        return preview;
    }

    /**
     * Sets the value of the preview property.
     * 
     * @param value
     *     allowed object is
     *     {@link FileType }
     *     
     */
    public void setPreview(FileType value) {
        this.preview = value;
    }

    /**
     * Gets the value of the icon property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the icon property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIcon().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FileType }
     * 
     * 
     */
    public List<FileType> getIcon() {
        if (icon == null) {
            icon = new ArrayList<FileType>();
        }
        return this.icon;
    }

    /**
     * Gets the value of the deviceIcon property.
     * 
     * @return
     *     possible object is
     *     {@link FileType }
     *     
     */
    public FileType getDeviceIcon() {
        return deviceIcon;
    }

    /**
     * Sets the value of the deviceIcon property.
     * 
     * @param value
     *     allowed object is
     *     {@link FileType }
     *     
     */
    public void setDeviceIcon(FileType value) {
        this.deviceIcon = value;
    }

    /**
     * Gets the value of the isDefault property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsDefault() {
        return isDefault;
    }

    /**
     * Sets the value of the isDefault property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsDefault(String value) {
        this.isDefault = value;
    }

    /**
     * Gets the value of the collectionName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCollectionName() {
        return collectionName;
    }

    /**
     * Sets the value of the collectionName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCollectionName(String value) {
        this.collectionName = value;
    }

    /**
     * Gets the value of the pricePlanPackage property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the pricePlanPackage property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPricePlanPackage().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RBTContent.PricePlanPackage }
     * 
     * 
     */
    public List<RBTContent.PricePlanPackage> getPricePlanPackage() {
        if (pricePlanPackage == null) {
            pricePlanPackage = new ArrayList<RBTContent.PricePlanPackage>();
        }
        return this.pricePlanPackage;
    }

    /**
     * Gets the value of the releaseYear property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getReleaseYear() {
        return releaseYear;
    }

    /**
     * Sets the value of the releaseYear property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setReleaseYear(Long value) {
        this.releaseYear = value;
    }

    /**
     * Gets the value of the isEnterprise property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsEnterprise() {
        return isEnterprise;
    }

    /**
     * Sets the value of the isEnterprise property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsEnterprise(String value) {
        this.isEnterprise = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;extension base="{http://www.vzw.com/namespaces/scmplus}PricePlanPackage-Type">
     *     &lt;/extension>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class PricePlanPackage
        extends PricePlanPackageType
    {


    }

}
