//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.31 at 10:31:22 AM EDT 
//


package com.vzwcorp.pricinglab.vo.mcs.ezcheckout;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CartLineItem" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{http://www.vzw.com/namespaces/scmplus}CartLineItemID"/>
 *                   &lt;element ref="{http://www.vzw.com/namespaces/scmplus}UserPreferences" maxOccurs="unbounded" minOccurs="0"/>
 *                   &lt;choice>
 *                     &lt;element name="Category">
 *                       &lt;complexType>
 *                         &lt;complexContent>
 *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                             &lt;sequence>
 *                               &lt;element ref="{http://www.vzw.com/namespaces/scmplus}CatID"/>
 *                               &lt;element ref="{http://www.vzw.com/namespaces/scmplus}CatName"/>
 *                               &lt;element name="PricePlanPackage">
 *                                 &lt;complexType>
 *                                   &lt;complexContent>
 *                                     &lt;extension base="{http://www.vzw.com/namespaces/scmplus}PricePlanPackage-Type">
 *                                     &lt;/extension>
 *                                   &lt;/complexContent>
 *                                 &lt;/complexType>
 *                               &lt;/element>
 *                               &lt;element name="IsWishlist" minOccurs="0">
 *                                 &lt;simpleType>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                     &lt;maxLength value="1"/>
 *                                     &lt;enumeration value="Y"/>
 *                                     &lt;enumeration value="N"/>
 *                                   &lt;/restriction>
 *                                 &lt;/simpleType>
 *                               &lt;/element>
 *                               &lt;element name="Artist" maxOccurs="unbounded" minOccurs="0">
 *                                 &lt;simpleType>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                     &lt;maxLength value="120"/>
 *                                   &lt;/restriction>
 *                                 &lt;/simpleType>
 *                               &lt;/element>
 *                               &lt;element ref="{http://www.vzw.com/namespaces/scmplus}CatDescription" minOccurs="0"/>
 *                               &lt;element ref="{http://www.vzw.com/namespaces/scmplus}CollectionType" minOccurs="0"/>
 *                               &lt;element ref="{http://www.vzw.com/namespaces/scmplus}IsExplicit" minOccurs="0"/>
 *                               &lt;element ref="{http://www.vzw.com/namespaces/scmplus}Icon" minOccurs="0"/>
 *                               &lt;element ref="{http://www.vzw.com/namespaces/scmplus}DeviceIcon" minOccurs="0"/>
 *                               &lt;element name="CountPerContent" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;/sequence>
 *                           &lt;/restriction>
 *                         &lt;/complexContent>
 *                       &lt;/complexType>
 *                     &lt;/element>
 *                     &lt;element name="Item">
 *                       &lt;complexType>
 *                         &lt;complexContent>
 *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                             &lt;sequence>
 *                               &lt;choice>
 *                                 &lt;element ref="{http://www.vzw.com/namespaces/scmplus}ItemID"/>
 *                                 &lt;sequence>
 *                                   &lt;element ref="{http://www.vzw.com/namespaces/scmplus}VendorID"/>
 *                                   &lt;element ref="{http://www.vzw.com/namespaces/scmplus}ContentID"/>
 *                                 &lt;/sequence>
 *                               &lt;/choice>
 *                               &lt;element ref="{http://www.vzw.com/namespaces/scmplus}ItemName"/>
 *                               &lt;element name="PricePlanPackage">
 *                                 &lt;complexType>
 *                                   &lt;complexContent>
 *                                     &lt;extension base="{http://www.vzw.com/namespaces/scmplus}PricePlanPackage-Type">
 *                                     &lt;/extension>
 *                                   &lt;/complexContent>
 *                                 &lt;/complexType>
 *                               &lt;/element>
 *                               &lt;element name="IsWishlist" minOccurs="0">
 *                                 &lt;simpleType>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                     &lt;maxLength value="1"/>
 *                                     &lt;enumeration value="Y"/>
 *                                     &lt;enumeration value="N"/>
 *                                   &lt;/restriction>
 *                                 &lt;/simpleType>
 *                               &lt;/element>
 *                               &lt;element ref="{http://www.vzw.com/namespaces/scmplus}ContentType" minOccurs="0"/>
 *                               &lt;element ref="{http://www.vzw.com/namespaces/scmplus}CollectionType" minOccurs="0"/>
 *                               &lt;element ref="{http://www.vzw.com/namespaces/scmplus}CollectionName" minOccurs="0"/>
 *                               &lt;element ref="{http://www.vzw.com/namespaces/scmplus}Artist" minOccurs="0"/>
 *                               &lt;element ref="{http://www.vzw.com/namespaces/scmplus}Icon" minOccurs="0"/>
 *                               &lt;element ref="{http://www.vzw.com/namespaces/scmplus}IsPartOfBundle" minOccurs="0"/>
 *                             &lt;/sequence>
 *                           &lt;/restriction>
 *                         &lt;/complexContent>
 *                       &lt;/complexType>
 *                     &lt;/element>
 *                     &lt;element name="Service">
 *                       &lt;complexType>
 *                         &lt;complexContent>
 *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                             &lt;sequence>
 *                               &lt;element ref="{http://www.vzw.com/namespaces/scmplus}ServiceID"/>
 *                               &lt;element ref="{http://www.vzw.com/namespaces/scmplus}ServiceName" minOccurs="0"/>
 *                               &lt;element name="PPPDesc" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                               &lt;element ref="{http://www.vzw.com/namespaces/scmplus}PurchasePrice" minOccurs="0"/>
 *                             &lt;/sequence>
 *                           &lt;/restriction>
 *                         &lt;/complexContent>
 *                       &lt;/complexType>
 *                     &lt;/element>
 *                     &lt;element name="ValuePak">
 *                       &lt;complexType>
 *                         &lt;complexContent>
 *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                             &lt;sequence>
 *                               &lt;element ref="{http://www.vzw.com/namespaces/scmplus}ValuePakID"/>
 *                               &lt;element ref="{http://www.vzw.com/namespaces/scmplus}PurchasePrice" minOccurs="0"/>
 *                             &lt;/sequence>
 *                           &lt;/restriction>
 *                         &lt;/complexContent>
 *                       &lt;/complexType>
 *                     &lt;/element>
 *                     &lt;element name="IsWishlist">
 *                       &lt;simpleType>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                           &lt;maxLength value="1"/>
 *                           &lt;enumeration value="Y"/>
 *                           &lt;enumeration value="N"/>
 *                         &lt;/restriction>
 *                       &lt;/simpleType>
 *                     &lt;/element>
 *                     &lt;element ref="{http://www.vzw.com/namespaces/scmplus}OrigFulfillmentID"/>
 *                   &lt;/choice>
 *                   &lt;element ref="{http://www.vzw.com/namespaces/scmplus}CheckoutPrice"/>
 *                   &lt;element ref="{http://www.vzw.com/namespaces/scmplus}NeededService" maxOccurs="unbounded" minOccurs="0"/>
 *                   &lt;element ref="{http://www.vzw.com/namespaces/scmplus}DiscountInfo" minOccurs="0"/>
 *                   &lt;choice>
 *                     &lt;element ref="{http://www.vzw.com/namespaces/scmplus}DestinationMdn" minOccurs="0"/>
 *                     &lt;element ref="{http://www.vzw.com/namespaces/scmplus}DestinationAcctRef" minOccurs="0"/>
 *                   &lt;/choice>
 *                   &lt;element name="ProrationInfo" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element ref="{http://www.vzw.com/namespaces/scmplus}ProrationAmount"/>
 *                             &lt;element ref="{http://www.vzw.com/namespaces/scmplus}TaxAmount" minOccurs="0"/>
 *                             &lt;element ref="{http://www.vzw.com/namespaces/scmplus}TaxDetails" maxOccurs="unbounded" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element ref="{http://www.vzw.com/namespaces/scmplus}TaxAmount" minOccurs="0"/>
 *                   &lt;element ref="{http://www.vzw.com/namespaces/scmplus}TaxDetails" maxOccurs="unbounded" minOccurs="0"/>
 *                   &lt;element ref="{http://www.vzw.com/namespaces/scmplus}SDA" minOccurs="0"/>
 *                   &lt;element ref="{http://www.vzw.com/namespaces/scmplus}LineRespMsg"/>
 *                   &lt;element name="ParentSeqID" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *                   &lt;element ref="{http://www.vzw.com/namespaces/scmplus}VendorTransactionID" minOccurs="0"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="seq" use="required" type="{http://www.w3.org/2001/XMLSchema}long" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element ref="{http://www.vzw.com/namespaces/scmplus}ConfirmationID" minOccurs="0"/>
 *         &lt;element ref="{http://www.vzw.com/namespaces/scmplus}TotalCheckoutPrice" minOccurs="0"/>
 *         &lt;element name="PrepayAccountBalance" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element ref="{http://www.vzw.com/namespaces/scmplus}DiscountDetails" minOccurs="0"/>
 *         &lt;element ref="{http://www.vzw.com/namespaces/scmplus}TaxAmount" minOccurs="0"/>
 *         &lt;element ref="{http://www.vzw.com/namespaces/scmplus}RespMsg"/>
 *         &lt;element ref="{http://www.vzw.com/namespaces/scmplus}Info" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "cartLineItem",
    "confirmationID",
    "totalCheckoutPrice",
    "prepayAccountBalance",
    "discountDetails",
    "taxAmount",
    "respMsg",
    "info"
})
@XmlRootElement(name = "RespCheckoutCart")
public class RespCheckoutCart {

    @XmlElement(name = "CartLineItem")
    protected List<RespCheckoutCart.CartLineItem> cartLineItem;
    @XmlElement(name = "ConfirmationID")
    protected String confirmationID;
    @XmlElement(name = "TotalCheckoutPrice")
    protected Double totalCheckoutPrice;
    @XmlElement(name = "PrepayAccountBalance")
    protected Double prepayAccountBalance;
    @XmlElement(name = "DiscountDetails")
    protected DiscountDetails discountDetails;
    @XmlElement(name = "TaxAmount")
    protected Double taxAmount;
    @XmlElement(name = "RespMsg", required = true)
    protected ResponseMsgType respMsg;
    @XmlElement(name = "Info")
    protected List<Info> info;

    /**
     * Gets the value of the cartLineItem property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the cartLineItem property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCartLineItem().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RespCheckoutCart.CartLineItem }
     * 
     * 
     */
    public List<RespCheckoutCart.CartLineItem> getCartLineItem() {
        if (cartLineItem == null) {
            cartLineItem = new ArrayList<RespCheckoutCart.CartLineItem>();
        }
        return this.cartLineItem;
    }

    /**
     * Gets the value of the confirmationID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConfirmationID() {
        return confirmationID;
    }

    /**
     * Sets the value of the confirmationID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConfirmationID(String value) {
        this.confirmationID = value;
    }

    /**
     * Gets the value of the totalCheckoutPrice property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getTotalCheckoutPrice() {
        return totalCheckoutPrice;
    }

    /**
     * Sets the value of the totalCheckoutPrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setTotalCheckoutPrice(Double value) {
        this.totalCheckoutPrice = value;
    }

    /**
     * Gets the value of the prepayAccountBalance property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getPrepayAccountBalance() {
        return prepayAccountBalance;
    }

    /**
     * Sets the value of the prepayAccountBalance property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setPrepayAccountBalance(Double value) {
        this.prepayAccountBalance = value;
    }

    /**
     * Gets the value of the discountDetails property.
     * 
     * @return
     *     possible object is
     *     {@link DiscountDetails }
     *     
     */
    public DiscountDetails getDiscountDetails() {
        return discountDetails;
    }

    /**
     * Sets the value of the discountDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link DiscountDetails }
     *     
     */
    public void setDiscountDetails(DiscountDetails value) {
        this.discountDetails = value;
    }

    /**
     * Gets the value of the taxAmount property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getTaxAmount() {
        return taxAmount;
    }

    /**
     * Sets the value of the taxAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setTaxAmount(Double value) {
        this.taxAmount = value;
    }

    /**
     * Gets the value of the respMsg property.
     * 
     * @return
     *     possible object is
     *     {@link ResponseMsgType }
     *     
     */
    public ResponseMsgType getRespMsg() {
        return respMsg;
    }

    /**
     * Sets the value of the respMsg property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResponseMsgType }
     *     
     */
    public void setRespMsg(ResponseMsgType value) {
        this.respMsg = value;
    }

    /**
     * Gets the value of the info property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the info property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInfo().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Info }
     * 
     * 
     */
    public List<Info> getInfo() {
        if (info == null) {
            info = new ArrayList<Info>();
        }
        return this.info;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{http://www.vzw.com/namespaces/scmplus}CartLineItemID"/>
     *         &lt;element ref="{http://www.vzw.com/namespaces/scmplus}UserPreferences" maxOccurs="unbounded" minOccurs="0"/>
     *         &lt;choice>
     *           &lt;element name="Category">
     *             &lt;complexType>
     *               &lt;complexContent>
     *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                   &lt;sequence>
     *                     &lt;element ref="{http://www.vzw.com/namespaces/scmplus}CatID"/>
     *                     &lt;element ref="{http://www.vzw.com/namespaces/scmplus}CatName"/>
     *                     &lt;element name="PricePlanPackage">
     *                       &lt;complexType>
     *                         &lt;complexContent>
     *                           &lt;extension base="{http://www.vzw.com/namespaces/scmplus}PricePlanPackage-Type">
     *                           &lt;/extension>
     *                         &lt;/complexContent>
     *                       &lt;/complexType>
     *                     &lt;/element>
     *                     &lt;element name="IsWishlist" minOccurs="0">
     *                       &lt;simpleType>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                           &lt;maxLength value="1"/>
     *                           &lt;enumeration value="Y"/>
     *                           &lt;enumeration value="N"/>
     *                         &lt;/restriction>
     *                       &lt;/simpleType>
     *                     &lt;/element>
     *                     &lt;element name="Artist" maxOccurs="unbounded" minOccurs="0">
     *                       &lt;simpleType>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                           &lt;maxLength value="120"/>
     *                         &lt;/restriction>
     *                       &lt;/simpleType>
     *                     &lt;/element>
     *                     &lt;element ref="{http://www.vzw.com/namespaces/scmplus}CatDescription" minOccurs="0"/>
     *                     &lt;element ref="{http://www.vzw.com/namespaces/scmplus}CollectionType" minOccurs="0"/>
     *                     &lt;element ref="{http://www.vzw.com/namespaces/scmplus}IsExplicit" minOccurs="0"/>
     *                     &lt;element ref="{http://www.vzw.com/namespaces/scmplus}Icon" minOccurs="0"/>
     *                     &lt;element ref="{http://www.vzw.com/namespaces/scmplus}DeviceIcon" minOccurs="0"/>
     *                     &lt;element name="CountPerContent" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;/sequence>
     *                 &lt;/restriction>
     *               &lt;/complexContent>
     *             &lt;/complexType>
     *           &lt;/element>
     *           &lt;element name="Item">
     *             &lt;complexType>
     *               &lt;complexContent>
     *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                   &lt;sequence>
     *                     &lt;choice>
     *                       &lt;element ref="{http://www.vzw.com/namespaces/scmplus}ItemID"/>
     *                       &lt;sequence>
     *                         &lt;element ref="{http://www.vzw.com/namespaces/scmplus}VendorID"/>
     *                         &lt;element ref="{http://www.vzw.com/namespaces/scmplus}ContentID"/>
     *                       &lt;/sequence>
     *                     &lt;/choice>
     *                     &lt;element ref="{http://www.vzw.com/namespaces/scmplus}ItemName"/>
     *                     &lt;element name="PricePlanPackage">
     *                       &lt;complexType>
     *                         &lt;complexContent>
     *                           &lt;extension base="{http://www.vzw.com/namespaces/scmplus}PricePlanPackage-Type">
     *                           &lt;/extension>
     *                         &lt;/complexContent>
     *                       &lt;/complexType>
     *                     &lt;/element>
     *                     &lt;element name="IsWishlist" minOccurs="0">
     *                       &lt;simpleType>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                           &lt;maxLength value="1"/>
     *                           &lt;enumeration value="Y"/>
     *                           &lt;enumeration value="N"/>
     *                         &lt;/restriction>
     *                       &lt;/simpleType>
     *                     &lt;/element>
     *                     &lt;element ref="{http://www.vzw.com/namespaces/scmplus}ContentType" minOccurs="0"/>
     *                     &lt;element ref="{http://www.vzw.com/namespaces/scmplus}CollectionType" minOccurs="0"/>
     *                     &lt;element ref="{http://www.vzw.com/namespaces/scmplus}CollectionName" minOccurs="0"/>
     *                     &lt;element ref="{http://www.vzw.com/namespaces/scmplus}Artist" minOccurs="0"/>
     *                     &lt;element ref="{http://www.vzw.com/namespaces/scmplus}Icon" minOccurs="0"/>
     *                     &lt;element ref="{http://www.vzw.com/namespaces/scmplus}IsPartOfBundle" minOccurs="0"/>
     *                   &lt;/sequence>
     *                 &lt;/restriction>
     *               &lt;/complexContent>
     *             &lt;/complexType>
     *           &lt;/element>
     *           &lt;element name="Service">
     *             &lt;complexType>
     *               &lt;complexContent>
     *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                   &lt;sequence>
     *                     &lt;element ref="{http://www.vzw.com/namespaces/scmplus}ServiceID"/>
     *                     &lt;element ref="{http://www.vzw.com/namespaces/scmplus}ServiceName" minOccurs="0"/>
     *                     &lt;element name="PPPDesc" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                     &lt;element ref="{http://www.vzw.com/namespaces/scmplus}PurchasePrice" minOccurs="0"/>
     *                   &lt;/sequence>
     *                 &lt;/restriction>
     *               &lt;/complexContent>
     *             &lt;/complexType>
     *           &lt;/element>
     *           &lt;element name="ValuePak">
     *             &lt;complexType>
     *               &lt;complexContent>
     *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                   &lt;sequence>
     *                     &lt;element ref="{http://www.vzw.com/namespaces/scmplus}ValuePakID"/>
     *                     &lt;element ref="{http://www.vzw.com/namespaces/scmplus}PurchasePrice" minOccurs="0"/>
     *                   &lt;/sequence>
     *                 &lt;/restriction>
     *               &lt;/complexContent>
     *             &lt;/complexType>
     *           &lt;/element>
     *           &lt;element name="IsWishlist">
     *             &lt;simpleType>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                 &lt;maxLength value="1"/>
     *                 &lt;enumeration value="Y"/>
     *                 &lt;enumeration value="N"/>
     *               &lt;/restriction>
     *             &lt;/simpleType>
     *           &lt;/element>
     *           &lt;element ref="{http://www.vzw.com/namespaces/scmplus}OrigFulfillmentID"/>
     *         &lt;/choice>
     *         &lt;element ref="{http://www.vzw.com/namespaces/scmplus}CheckoutPrice"/>
     *         &lt;element ref="{http://www.vzw.com/namespaces/scmplus}NeededService" maxOccurs="unbounded" minOccurs="0"/>
     *         &lt;element ref="{http://www.vzw.com/namespaces/scmplus}DiscountInfo" minOccurs="0"/>
     *         &lt;choice>
     *           &lt;element ref="{http://www.vzw.com/namespaces/scmplus}DestinationMdn" minOccurs="0"/>
     *           &lt;element ref="{http://www.vzw.com/namespaces/scmplus}DestinationAcctRef" minOccurs="0"/>
     *         &lt;/choice>
     *         &lt;element name="ProrationInfo" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element ref="{http://www.vzw.com/namespaces/scmplus}ProrationAmount"/>
     *                   &lt;element ref="{http://www.vzw.com/namespaces/scmplus}TaxAmount" minOccurs="0"/>
     *                   &lt;element ref="{http://www.vzw.com/namespaces/scmplus}TaxDetails" maxOccurs="unbounded" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element ref="{http://www.vzw.com/namespaces/scmplus}TaxAmount" minOccurs="0"/>
     *         &lt;element ref="{http://www.vzw.com/namespaces/scmplus}TaxDetails" maxOccurs="unbounded" minOccurs="0"/>
     *         &lt;element ref="{http://www.vzw.com/namespaces/scmplus}SDA" minOccurs="0"/>
     *         &lt;element ref="{http://www.vzw.com/namespaces/scmplus}LineRespMsg"/>
     *         &lt;element name="ParentSeqID" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
     *         &lt;element ref="{http://www.vzw.com/namespaces/scmplus}VendorTransactionID" minOccurs="0"/>
     *       &lt;/sequence>
     *       &lt;attribute name="seq" use="required" type="{http://www.w3.org/2001/XMLSchema}long" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "cartLineItemID",
        "userPreferences",
        "category",
        "item",
        "service",
        "valuePak",
        "isWishlist",
        "origFulfillmentID",
        "checkoutPrice",
        "neededService",
        "discountInfo",
        "destinationMdn",
        "destinationAcctRef",
        "prorationInfo",
        "taxAmount",
        "taxDetails",
        "sda",
        "lineRespMsg",
        "parentSeqID",
        "vendorTransactionID"
    })
    public static class CartLineItem {

        @XmlElement(name = "CartLineItemID")
        protected long cartLineItemID;
        @XmlElement(name = "UserPreferences")
        protected List<UserPreferences> userPreferences;
        @XmlElement(name = "Category")
        protected RespCheckoutCart.CartLineItem.Category category;
        @XmlElement(name = "Item")
        protected RespCheckoutCart.CartLineItem.Item item;
        @XmlElement(name = "Service")
        protected RespCheckoutCart.CartLineItem.Service service;
        @XmlElement(name = "ValuePak")
        protected RespCheckoutCart.CartLineItem.ValuePak valuePak;
        @XmlElement(name = "IsWishlist")
        protected String isWishlist;
        @XmlElement(name = "OrigFulfillmentID")
        protected String origFulfillmentID;
        @XmlElement(name = "CheckoutPrice")
        protected double checkoutPrice;
        @XmlElement(name = "NeededService")
        protected List<NeededService> neededService;
        @XmlElement(name = "DiscountInfo")
        protected DiscountInfo discountInfo;
        @XmlElement(name = "DestinationMdn")
        protected Long destinationMdn;
        @XmlElement(name = "DestinationAcctRef")
        protected String destinationAcctRef;
        @XmlElement(name = "ProrationInfo")
        protected RespCheckoutCart.CartLineItem.ProrationInfo prorationInfo;
        @XmlElement(name = "TaxAmount")
        protected Double taxAmount;
        @XmlElement(name = "TaxDetails")
        protected List<TaxDetails> taxDetails;
        @XmlElement(name = "SDA")
        protected SDA sda;
        @XmlElement(name = "LineRespMsg", required = true)
        protected ResponseMsgType lineRespMsg;
        @XmlElement(name = "ParentSeqID")
        protected Long parentSeqID;
        @XmlElement(name = "VendorTransactionID")
        protected String vendorTransactionID;
        @XmlAttribute(name = "seq", required = true)
        protected long seq;

        /**
         * Gets the value of the cartLineItemID property.
         * 
         */
        public long getCartLineItemID() {
            return cartLineItemID;
        }

        /**
         * Sets the value of the cartLineItemID property.
         * 
         */
        public void setCartLineItemID(long value) {
            this.cartLineItemID = value;
        }

        /**
         * Gets the value of the userPreferences property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the userPreferences property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getUserPreferences().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link UserPreferences }
         * 
         * 
         */
        public List<UserPreferences> getUserPreferences() {
            if (userPreferences == null) {
                userPreferences = new ArrayList<UserPreferences>();
            }
            return this.userPreferences;
        }

        /**
         * Gets the value of the category property.
         * 
         * @return
         *     possible object is
         *     {@link RespCheckoutCart.CartLineItem.Category }
         *     
         */
        public RespCheckoutCart.CartLineItem.Category getCategory() {
            return category;
        }

        /**
         * Sets the value of the category property.
         * 
         * @param value
         *     allowed object is
         *     {@link RespCheckoutCart.CartLineItem.Category }
         *     
         */
        public void setCategory(RespCheckoutCart.CartLineItem.Category value) {
            this.category = value;
        }

        /**
         * Gets the value of the item property.
         * 
         * @return
         *     possible object is
         *     {@link RespCheckoutCart.CartLineItem.Item }
         *     
         */
        public RespCheckoutCart.CartLineItem.Item getItem() {
            return item;
        }

        /**
         * Sets the value of the item property.
         * 
         * @param value
         *     allowed object is
         *     {@link RespCheckoutCart.CartLineItem.Item }
         *     
         */
        public void setItem(RespCheckoutCart.CartLineItem.Item value) {
            this.item = value;
        }

        /**
         * Gets the value of the service property.
         * 
         * @return
         *     possible object is
         *     {@link RespCheckoutCart.CartLineItem.Service }
         *     
         */
        public RespCheckoutCart.CartLineItem.Service getService() {
            return service;
        }

        /**
         * Sets the value of the service property.
         * 
         * @param value
         *     allowed object is
         *     {@link RespCheckoutCart.CartLineItem.Service }
         *     
         */
        public void setService(RespCheckoutCart.CartLineItem.Service value) {
            this.service = value;
        }

        /**
         * Gets the value of the valuePak property.
         * 
         * @return
         *     possible object is
         *     {@link RespCheckoutCart.CartLineItem.ValuePak }
         *     
         */
        public RespCheckoutCart.CartLineItem.ValuePak getValuePak() {
            return valuePak;
        }

        /**
         * Sets the value of the valuePak property.
         * 
         * @param value
         *     allowed object is
         *     {@link RespCheckoutCart.CartLineItem.ValuePak }
         *     
         */
        public void setValuePak(RespCheckoutCart.CartLineItem.ValuePak value) {
            this.valuePak = value;
        }

        /**
         * Gets the value of the isWishlist property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getIsWishlist() {
            return isWishlist;
        }

        /**
         * Sets the value of the isWishlist property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setIsWishlist(String value) {
            this.isWishlist = value;
        }

        /**
         * Gets the value of the origFulfillmentID property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getOrigFulfillmentID() {
            return origFulfillmentID;
        }

        /**
         * Sets the value of the origFulfillmentID property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setOrigFulfillmentID(String value) {
            this.origFulfillmentID = value;
        }

        /**
         * Gets the value of the checkoutPrice property.
         * 
         */
        public double getCheckoutPrice() {
            return checkoutPrice;
        }

        /**
         * Sets the value of the checkoutPrice property.
         * 
         */
        public void setCheckoutPrice(double value) {
            this.checkoutPrice = value;
        }

        /**
         * Gets the value of the neededService property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the neededService property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getNeededService().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link NeededService }
         * 
         * 
         */
        public List<NeededService> getNeededService() {
            if (neededService == null) {
                neededService = new ArrayList<NeededService>();
            }
            return this.neededService;
        }

        /**
         * Gets the value of the discountInfo property.
         * 
         * @return
         *     possible object is
         *     {@link DiscountInfo }
         *     
         */
        public DiscountInfo getDiscountInfo() {
            return discountInfo;
        }

        /**
         * Sets the value of the discountInfo property.
         * 
         * @param value
         *     allowed object is
         *     {@link DiscountInfo }
         *     
         */
        public void setDiscountInfo(DiscountInfo value) {
            this.discountInfo = value;
        }

        /**
         * Gets the value of the destinationMdn property.
         * 
         * @return
         *     possible object is
         *     {@link Long }
         *     
         */
        public Long getDestinationMdn() {
            return destinationMdn;
        }

        /**
         * Sets the value of the destinationMdn property.
         * 
         * @param value
         *     allowed object is
         *     {@link Long }
         *     
         */
        public void setDestinationMdn(Long value) {
            this.destinationMdn = value;
        }

        /**
         * Gets the value of the destinationAcctRef property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDestinationAcctRef() {
            return destinationAcctRef;
        }

        /**
         * Sets the value of the destinationAcctRef property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDestinationAcctRef(String value) {
            this.destinationAcctRef = value;
        }

        /**
         * Gets the value of the prorationInfo property.
         * 
         * @return
         *     possible object is
         *     {@link RespCheckoutCart.CartLineItem.ProrationInfo }
         *     
         */
        public RespCheckoutCart.CartLineItem.ProrationInfo getProrationInfo() {
            return prorationInfo;
        }

        /**
         * Sets the value of the prorationInfo property.
         * 
         * @param value
         *     allowed object is
         *     {@link RespCheckoutCart.CartLineItem.ProrationInfo }
         *     
         */
        public void setProrationInfo(RespCheckoutCart.CartLineItem.ProrationInfo value) {
            this.prorationInfo = value;
        }

        /**
         * Gets the value of the taxAmount property.
         * 
         * @return
         *     possible object is
         *     {@link Double }
         *     
         */
        public Double getTaxAmount() {
            return taxAmount;
        }

        /**
         * Sets the value of the taxAmount property.
         * 
         * @param value
         *     allowed object is
         *     {@link Double }
         *     
         */
        public void setTaxAmount(Double value) {
            this.taxAmount = value;
        }

        /**
         * Gets the value of the taxDetails property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the taxDetails property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getTaxDetails().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link TaxDetails }
         * 
         * 
         */
        public List<TaxDetails> getTaxDetails() {
            if (taxDetails == null) {
                taxDetails = new ArrayList<TaxDetails>();
            }
            return this.taxDetails;
        }

        /**
         * Gets the value of the sda property.
         * 
         * @return
         *     possible object is
         *     {@link SDA }
         *     
         */
        public SDA getSDA() {
            return sda;
        }

        /**
         * Sets the value of the sda property.
         * 
         * @param value
         *     allowed object is
         *     {@link SDA }
         *     
         */
        public void setSDA(SDA value) {
            this.sda = value;
        }

        /**
         * Gets the value of the lineRespMsg property.
         * 
         * @return
         *     possible object is
         *     {@link ResponseMsgType }
         *     
         */
        public ResponseMsgType getLineRespMsg() {
            return lineRespMsg;
        }

        /**
         * Sets the value of the lineRespMsg property.
         * 
         * @param value
         *     allowed object is
         *     {@link ResponseMsgType }
         *     
         */
        public void setLineRespMsg(ResponseMsgType value) {
            this.lineRespMsg = value;
        }

        /**
         * Gets the value of the parentSeqID property.
         * 
         * @return
         *     possible object is
         *     {@link Long }
         *     
         */
        public Long getParentSeqID() {
            return parentSeqID;
        }

        /**
         * Sets the value of the parentSeqID property.
         * 
         * @param value
         *     allowed object is
         *     {@link Long }
         *     
         */
        public void setParentSeqID(Long value) {
            this.parentSeqID = value;
        }

        /**
         * Gets the value of the vendorTransactionID property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getVendorTransactionID() {
            return vendorTransactionID;
        }

        /**
         * Sets the value of the vendorTransactionID property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setVendorTransactionID(String value) {
            this.vendorTransactionID = value;
        }

        /**
         * Gets the value of the seq property.
         * 
         */
        public long getSeq() {
            return seq;
        }

        /**
         * Sets the value of the seq property.
         * 
         */
        public void setSeq(long value) {
            this.seq = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element ref="{http://www.vzw.com/namespaces/scmplus}CatID"/>
         *         &lt;element ref="{http://www.vzw.com/namespaces/scmplus}CatName"/>
         *         &lt;element name="PricePlanPackage">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;extension base="{http://www.vzw.com/namespaces/scmplus}PricePlanPackage-Type">
         *               &lt;/extension>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="IsWishlist" minOccurs="0">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;maxLength value="1"/>
         *               &lt;enumeration value="Y"/>
         *               &lt;enumeration value="N"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="Artist" maxOccurs="unbounded" minOccurs="0">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;maxLength value="120"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element ref="{http://www.vzw.com/namespaces/scmplus}CatDescription" minOccurs="0"/>
         *         &lt;element ref="{http://www.vzw.com/namespaces/scmplus}CollectionType" minOccurs="0"/>
         *         &lt;element ref="{http://www.vzw.com/namespaces/scmplus}IsExplicit" minOccurs="0"/>
         *         &lt;element ref="{http://www.vzw.com/namespaces/scmplus}Icon" minOccurs="0"/>
         *         &lt;element ref="{http://www.vzw.com/namespaces/scmplus}DeviceIcon" minOccurs="0"/>
         *         &lt;element name="CountPerContent" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "catID",
            "catName",
            "pricePlanPackage",
            "isWishlist",
            "artist",
            "catDescription",
            "collectionType",
            "isExplicit",
            "icon",
            "deviceIcon",
            "countPerContent"
        })
        public static class Category {

            @XmlElement(name = "CatID", required = true)
            protected String catID;
            @XmlElement(name = "CatName", required = true)
            protected String catName;
            @XmlElement(name = "PricePlanPackage", required = true)
            protected RespCheckoutCart.CartLineItem.Category.PricePlanPackage pricePlanPackage;
            @XmlElement(name = "IsWishlist")
            protected String isWishlist;
            @XmlElement(name = "Artist")
            protected List<String> artist;
            @XmlElement(name = "CatDescription")
            protected String catDescription;
            @XmlElement(name = "CollectionType")
            protected String collectionType;
            @XmlElement(name = "IsExplicit")
            protected Boolean isExplicit;
            @XmlElement(name = "Icon")
            protected FileType icon;
            @XmlElement(name = "DeviceIcon")
            protected FileType deviceIcon;
            @XmlElement(name = "CountPerContent")
            protected String countPerContent;

            /**
             * Gets the value of the catID property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCatID() {
                return catID;
            }

            /**
             * Sets the value of the catID property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCatID(String value) {
                this.catID = value;
            }

            /**
             * Gets the value of the catName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCatName() {
                return catName;
            }

            /**
             * Sets the value of the catName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCatName(String value) {
                this.catName = value;
            }

            /**
             * Gets the value of the pricePlanPackage property.
             * 
             * @return
             *     possible object is
             *     {@link RespCheckoutCart.CartLineItem.Category.PricePlanPackage }
             *     
             */
            public RespCheckoutCart.CartLineItem.Category.PricePlanPackage getPricePlanPackage() {
                return pricePlanPackage;
            }

            /**
             * Sets the value of the pricePlanPackage property.
             * 
             * @param value
             *     allowed object is
             *     {@link RespCheckoutCart.CartLineItem.Category.PricePlanPackage }
             *     
             */
            public void setPricePlanPackage(RespCheckoutCart.CartLineItem.Category.PricePlanPackage value) {
                this.pricePlanPackage = value;
            }

            /**
             * Gets the value of the isWishlist property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getIsWishlist() {
                return isWishlist;
            }

            /**
             * Sets the value of the isWishlist property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setIsWishlist(String value) {
                this.isWishlist = value;
            }

            /**
             * Gets the value of the artist property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the artist property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getArtist().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link String }
             * 
             * 
             */
            public List<String> getArtist() {
                if (artist == null) {
                    artist = new ArrayList<String>();
                }
                return this.artist;
            }

            /**
             * Gets the value of the catDescription property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCatDescription() {
                return catDescription;
            }

            /**
             * Sets the value of the catDescription property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCatDescription(String value) {
                this.catDescription = value;
            }

            /**
             * Gets the value of the collectionType property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCollectionType() {
                return collectionType;
            }

            /**
             * Sets the value of the collectionType property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCollectionType(String value) {
                this.collectionType = value;
            }

            /**
             * Gets the value of the isExplicit property.
             * 
             * @return
             *     possible object is
             *     {@link Boolean }
             *     
             */
            public Boolean isIsExplicit() {
                return isExplicit;
            }

            /**
             * Sets the value of the isExplicit property.
             * 
             * @param value
             *     allowed object is
             *     {@link Boolean }
             *     
             */
            public void setIsExplicit(Boolean value) {
                this.isExplicit = value;
            }

            /**
             * Gets the value of the icon property.
             * 
             * @return
             *     possible object is
             *     {@link FileType }
             *     
             */
            public FileType getIcon() {
                return icon;
            }

            /**
             * Sets the value of the icon property.
             * 
             * @param value
             *     allowed object is
             *     {@link FileType }
             *     
             */
            public void setIcon(FileType value) {
                this.icon = value;
            }

            /**
             * Gets the value of the deviceIcon property.
             * 
             * @return
             *     possible object is
             *     {@link FileType }
             *     
             */
            public FileType getDeviceIcon() {
                return deviceIcon;
            }

            /**
             * Sets the value of the deviceIcon property.
             * 
             * @param value
             *     allowed object is
             *     {@link FileType }
             *     
             */
            public void setDeviceIcon(FileType value) {
                this.deviceIcon = value;
            }

            /**
             * Gets the value of the countPerContent property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCountPerContent() {
                return countPerContent;
            }

            /**
             * Sets the value of the countPerContent property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCountPerContent(String value) {
                this.countPerContent = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;extension base="{http://www.vzw.com/namespaces/scmplus}PricePlanPackage-Type">
             *     &lt;/extension>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "")
            public static class PricePlanPackage
                extends PricePlanPackageType
            {


            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;choice>
         *           &lt;element ref="{http://www.vzw.com/namespaces/scmplus}ItemID"/>
         *           &lt;sequence>
         *             &lt;element ref="{http://www.vzw.com/namespaces/scmplus}VendorID"/>
         *             &lt;element ref="{http://www.vzw.com/namespaces/scmplus}ContentID"/>
         *           &lt;/sequence>
         *         &lt;/choice>
         *         &lt;element ref="{http://www.vzw.com/namespaces/scmplus}ItemName"/>
         *         &lt;element name="PricePlanPackage">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;extension base="{http://www.vzw.com/namespaces/scmplus}PricePlanPackage-Type">
         *               &lt;/extension>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="IsWishlist" minOccurs="0">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;maxLength value="1"/>
         *               &lt;enumeration value="Y"/>
         *               &lt;enumeration value="N"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element ref="{http://www.vzw.com/namespaces/scmplus}ContentType" minOccurs="0"/>
         *         &lt;element ref="{http://www.vzw.com/namespaces/scmplus}CollectionType" minOccurs="0"/>
         *         &lt;element ref="{http://www.vzw.com/namespaces/scmplus}CollectionName" minOccurs="0"/>
         *         &lt;element ref="{http://www.vzw.com/namespaces/scmplus}Artist" minOccurs="0"/>
         *         &lt;element ref="{http://www.vzw.com/namespaces/scmplus}Icon" minOccurs="0"/>
         *         &lt;element ref="{http://www.vzw.com/namespaces/scmplus}IsPartOfBundle" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "itemID",
            "vendorID",
            "contentID",
            "itemName",
            "pricePlanPackage",
            "isWishlist",
            "contentType",
            "collectionType",
            "collectionName",
            "artist",
            "icon",
            "isPartOfBundle"
        })
        public static class Item {

            @XmlElement(name = "ItemID")
            protected String itemID;
            @XmlElement(name = "VendorID")
            protected String vendorID;
            @XmlElement(name = "ContentID")
            protected String contentID;
            @XmlElement(name = "ItemName", required = true)
            protected String itemName;
            @XmlElement(name = "PricePlanPackage", required = true)
            protected RespCheckoutCart.CartLineItem.Item.PricePlanPackage pricePlanPackage;
            @XmlElement(name = "IsWishlist")
            protected String isWishlist;
            @XmlElement(name = "ContentType")
            protected String contentType;
            @XmlElement(name = "CollectionType")
            protected String collectionType;
            @XmlElement(name = "CollectionName")
            protected String collectionName;
            @XmlElement(name = "Artist")
            protected String artist;
            @XmlElement(name = "Icon")
            protected FileType icon;
            @XmlElement(name = "IsPartOfBundle")
            protected Boolean isPartOfBundle;

            /**
             * Gets the value of the itemID property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getItemID() {
                return itemID;
            }

            /**
             * Sets the value of the itemID property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setItemID(String value) {
                this.itemID = value;
            }

            /**
             * Gets the value of the vendorID property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getVendorID() {
                return vendorID;
            }

            /**
             * Sets the value of the vendorID property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setVendorID(String value) {
                this.vendorID = value;
            }

            /**
             * Gets the value of the contentID property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getContentID() {
                return contentID;
            }

            /**
             * Sets the value of the contentID property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setContentID(String value) {
                this.contentID = value;
            }

            /**
             * Gets the value of the itemName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getItemName() {
                return itemName;
            }

            /**
             * Sets the value of the itemName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setItemName(String value) {
                this.itemName = value;
            }

            /**
             * Gets the value of the pricePlanPackage property.
             * 
             * @return
             *     possible object is
             *     {@link RespCheckoutCart.CartLineItem.Item.PricePlanPackage }
             *     
             */
            public RespCheckoutCart.CartLineItem.Item.PricePlanPackage getPricePlanPackage() {
                return pricePlanPackage;
            }

            /**
             * Sets the value of the pricePlanPackage property.
             * 
             * @param value
             *     allowed object is
             *     {@link RespCheckoutCart.CartLineItem.Item.PricePlanPackage }
             *     
             */
            public void setPricePlanPackage(RespCheckoutCart.CartLineItem.Item.PricePlanPackage value) {
                this.pricePlanPackage = value;
            }

            /**
             * Gets the value of the isWishlist property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getIsWishlist() {
                return isWishlist;
            }

            /**
             * Sets the value of the isWishlist property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setIsWishlist(String value) {
                this.isWishlist = value;
            }

            /**
             * Gets the value of the contentType property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getContentType() {
                return contentType;
            }

            /**
             * Sets the value of the contentType property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setContentType(String value) {
                this.contentType = value;
            }

            /**
             * Gets the value of the collectionType property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCollectionType() {
                return collectionType;
            }

            /**
             * Sets the value of the collectionType property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCollectionType(String value) {
                this.collectionType = value;
            }

            /**
             * Gets the value of the collectionName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCollectionName() {
                return collectionName;
            }

            /**
             * Sets the value of the collectionName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCollectionName(String value) {
                this.collectionName = value;
            }

            /**
             * Gets the value of the artist property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getArtist() {
                return artist;
            }

            /**
             * Sets the value of the artist property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setArtist(String value) {
                this.artist = value;
            }

            /**
             * Gets the value of the icon property.
             * 
             * @return
             *     possible object is
             *     {@link FileType }
             *     
             */
            public FileType getIcon() {
                return icon;
            }

            /**
             * Sets the value of the icon property.
             * 
             * @param value
             *     allowed object is
             *     {@link FileType }
             *     
             */
            public void setIcon(FileType value) {
                this.icon = value;
            }

            /**
             * Gets the value of the isPartOfBundle property.
             * 
             * @return
             *     possible object is
             *     {@link Boolean }
             *     
             */
            public Boolean isIsPartOfBundle() {
                return isPartOfBundle;
            }

            /**
             * Sets the value of the isPartOfBundle property.
             * 
             * @param value
             *     allowed object is
             *     {@link Boolean }
             *     
             */
            public void setIsPartOfBundle(Boolean value) {
                this.isPartOfBundle = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;extension base="{http://www.vzw.com/namespaces/scmplus}PricePlanPackage-Type">
             *     &lt;/extension>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "")
            public static class PricePlanPackage
                extends PricePlanPackageType
            {


            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element ref="{http://www.vzw.com/namespaces/scmplus}ProrationAmount"/>
         *         &lt;element ref="{http://www.vzw.com/namespaces/scmplus}TaxAmount" minOccurs="0"/>
         *         &lt;element ref="{http://www.vzw.com/namespaces/scmplus}TaxDetails" maxOccurs="unbounded" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "prorationAmount",
            "taxAmount",
            "taxDetails"
        })
        public static class ProrationInfo {

            @XmlElement(name = "ProrationAmount")
            protected double prorationAmount;
            @XmlElement(name = "TaxAmount")
            protected Double taxAmount;
            @XmlElement(name = "TaxDetails")
            protected List<TaxDetails> taxDetails;

            /**
             * Gets the value of the prorationAmount property.
             * 
             */
            public double getProrationAmount() {
                return prorationAmount;
            }

            /**
             * Sets the value of the prorationAmount property.
             * 
             */
            public void setProrationAmount(double value) {
                this.prorationAmount = value;
            }

            /**
             * Gets the value of the taxAmount property.
             * 
             * @return
             *     possible object is
             *     {@link Double }
             *     
             */
            public Double getTaxAmount() {
                return taxAmount;
            }

            /**
             * Sets the value of the taxAmount property.
             * 
             * @param value
             *     allowed object is
             *     {@link Double }
             *     
             */
            public void setTaxAmount(Double value) {
                this.taxAmount = value;
            }

            /**
             * Gets the value of the taxDetails property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the taxDetails property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getTaxDetails().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link TaxDetails }
             * 
             * 
             */
            public List<TaxDetails> getTaxDetails() {
                if (taxDetails == null) {
                    taxDetails = new ArrayList<TaxDetails>();
                }
                return this.taxDetails;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element ref="{http://www.vzw.com/namespaces/scmplus}ServiceID"/>
         *         &lt;element ref="{http://www.vzw.com/namespaces/scmplus}ServiceName" minOccurs="0"/>
         *         &lt;element name="PPPDesc" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element ref="{http://www.vzw.com/namespaces/scmplus}PurchasePrice" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "serviceID",
            "serviceName",
            "pppDesc",
            "purchasePrice"
        })
        public static class Service {

            @XmlElement(name = "ServiceID", required = true)
            protected String serviceID;
            @XmlElement(name = "ServiceName")
            protected String serviceName;
            @XmlElement(name = "PPPDesc")
            protected String pppDesc;
            @XmlElement(name = "PurchasePrice")
            protected Double purchasePrice;

            /**
             * Gets the value of the serviceID property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getServiceID() {
                return serviceID;
            }

            /**
             * Sets the value of the serviceID property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setServiceID(String value) {
                this.serviceID = value;
            }

            /**
             * Gets the value of the serviceName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getServiceName() {
                return serviceName;
            }

            /**
             * Sets the value of the serviceName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setServiceName(String value) {
                this.serviceName = value;
            }

            /**
             * Gets the value of the pppDesc property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPPPDesc() {
                return pppDesc;
            }

            /**
             * Sets the value of the pppDesc property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPPPDesc(String value) {
                this.pppDesc = value;
            }

            /**
             * Gets the value of the purchasePrice property.
             * 
             * @return
             *     possible object is
             *     {@link Double }
             *     
             */
            public Double getPurchasePrice() {
                return purchasePrice;
            }

            /**
             * Sets the value of the purchasePrice property.
             * 
             * @param value
             *     allowed object is
             *     {@link Double }
             *     
             */
            public void setPurchasePrice(Double value) {
                this.purchasePrice = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element ref="{http://www.vzw.com/namespaces/scmplus}ValuePakID"/>
         *         &lt;element ref="{http://www.vzw.com/namespaces/scmplus}PurchasePrice" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "valuePakID",
            "purchasePrice"
        })
        public static class ValuePak {

            @XmlElement(name = "ValuePakID")
            protected int valuePakID;
            @XmlElement(name = "PurchasePrice")
            protected Double purchasePrice;

            /**
             * Gets the value of the valuePakID property.
             * 
             */
            public int getValuePakID() {
                return valuePakID;
            }

            /**
             * Sets the value of the valuePakID property.
             * 
             */
            public void setValuePakID(int value) {
                this.valuePakID = value;
            }

            /**
             * Gets the value of the purchasePrice property.
             * 
             * @return
             *     possible object is
             *     {@link Double }
             *     
             */
            public Double getPurchasePrice() {
                return purchasePrice;
            }

            /**
             * Sets the value of the purchasePrice property.
             * 
             * @param value
             *     allowed object is
             *     {@link Double }
             *     
             */
            public void setPurchasePrice(Double value) {
                this.purchasePrice = value;
            }

        }

    }

}
