//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.31 at 10:31:22 AM EDT 
//


package com.vzwcorp.pricinglab.vo.mcs.ezcheckout;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Details of SfMtn
 * 
 * <p>Java class for SfMtnType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SfMtnType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Mdn" type="{http://www.vzw.com/namespaces/scmplus}NEW_MDNType"/>
 *         &lt;element name="MtnEffDt" type="{http://www.vzw.com/namespaces/scmplus}Date" minOccurs="0"/>
 *         &lt;element name="SFOList" type="{http://www.vzw.com/namespaces/scmplus}SFOListType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SfMtnType", propOrder = {
    "mdn",
    "mtnEffDt",
    "sfoList"
})
public class SfMtnType {

    @XmlElement(name = "Mdn", required = true)
    protected String mdn;
    @XmlElement(name = "MtnEffDt")
    protected String mtnEffDt;
    @XmlElement(name = "SFOList", required = true)
    protected SFOListType sfoList;

    /**
     * Gets the value of the mdn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMdn() {
        return mdn;
    }

    /**
     * Sets the value of the mdn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMdn(String value) {
        this.mdn = value;
    }

    /**
     * Gets the value of the mtnEffDt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMtnEffDt() {
        return mtnEffDt;
    }

    /**
     * Sets the value of the mtnEffDt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMtnEffDt(String value) {
        this.mtnEffDt = value;
    }

    /**
     * Gets the value of the sfoList property.
     * 
     * @return
     *     possible object is
     *     {@link SFOListType }
     *     
     */
    public SFOListType getSFOList() {
        return sfoList;
    }

    /**
     * Sets the value of the sfoList property.
     * 
     * @param value
     *     allowed object is
     *     {@link SFOListType }
     *     
     */
    public void setSFOList(SFOListType value) {
        this.sfoList = value;
    }

}
